import type {
  Announcement,
  AppNotification,
  AppUser,
  AttendanceRecord,
  Company,
  CompanyRequest,
  Deduction,
  Employee,
  LeaveRequest,
  Loan,
  PerformanceReview,
} from "./types";

const today = new Date().toISOString().slice(0, 10);

export const SEED_LEAVES: LeaveRequest[] = [
  {
    id: "lv-1",
    companyId: "c-alfajr",
    employeeId: "e-1003",
    employeeName: "خالد ناصر الشمري",
    type: "ANNUAL",
    startDate: "2026-07-05",
    endDate: "2026-07-09",
    days: 5,
    reason: "إجازة سنوية",
    status: "PENDING",
    createdAt: today,
  },
  {
    id: "lv-2",
    companyId: "c-alfajr",
    employeeId: "e-1002",
    employeeName: "سارة فهد العتيبي",
    type: "SICK",
    startDate: "2026-06-22",
    endDate: "2026-06-23",
    days: 2,
    reason: "إجازة مرضية",
    status: "APPROVED",
    createdAt: "2026-06-21",
  },
  {
    id: "lv-3",
    companyId: "c-noor",
    employeeId: "e-2002",
    employeeName: "نوف عبدالعزيز الدوسري",
    type: "ANNUAL",
    startDate: "2026-08-01",
    endDate: "2026-08-10",
    days: 10,
    reason: "سفر",
    status: "PENDING",
    createdAt: today,
  },
];

export const SEED_REQUESTS: CompanyRequest[] = [
  {
    id: "rq-1",
    companyId: "c-alfajr",
    employeeId: "e-1001",
    employeeName: "عبدالله محمد القحطاني",
    kind: "REMOTE",
    date: "2026-07-02",
    reason: "متابعة مشروع عن بُعد",
    status: "PENDING",
    createdAt: today,
  },
  {
    id: "rq-2",
    companyId: "c-alfajr",
    employeeId: "e-1003",
    employeeName: "خالد ناصر الشمري",
    kind: "LOAN",
    amount: 15000,
    installments: 10,
    reason: "سلفة شخصية",
    status: "PENDING",
    createdAt: today,
  },
  {
    id: "rq-3",
    companyId: "c-alfajr",
    employeeId: "e-1002",
    employeeName: "سارة فهد العتيبي",
    kind: "PERMISSION",
    date: "2026-06-29",
    hours: 2,
    reason: "مراجعة جهة حكومية",
    status: "APPROVED",
    createdAt: "2026-06-27",
  },
  {
    id: "rq-4",
    companyId: "c-noor",
    employeeId: "e-2002",
    employeeName: "نوف عبدالعزيز الدوسري",
    kind: "DOCUMENT",
    docType: "تعريف بالراتب",
    reason: "فتح حساب بنكي",
    status: "PENDING",
    createdAt: today,
  },
];

export const SEED_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "an-1",
    companyId: "c-alfajr",
    title: "تحديث مواعيد الدوام في رمضان",
    content: "نُعلمكم بأن مواعيد الدوام خلال شهر رمضان المبارك ستكون من العاشرة صباحاً حتى الرابعة عصراً.",
    audience: "ALL",
    recipients: 3,
    createdByName: "إدارة الموارد البشرية",
    createdAt: "2026-06-20",
  },
  {
    id: "an-2",
    companyId: "c-alfajr",
    title: "اجتماع قسم المالية",
    content: "اجتماع مراجعة الإقفال الشهري يوم الأحد القادم في قاعة الاجتماعات الرئيسية.",
    audience: "DEPARTMENT",
    targetDept: "المالية",
    recipients: 1,
    createdByName: "إدارة الموارد البشرية",
    createdAt: "2026-06-25",
  },
];

export const SEED_NOTIFICATIONS: AppNotification[] = [
  { id: "nt-1", companyId: "c-alfajr", title: "طلب جديد", body: "طلب عمل عن بُعد من عبدالله محمد القحطاني بانتظار الاعتماد.", type: "REQUEST", read: false, createdAt: new Date(Date.now() - 3600000).toISOString() },
  { id: "nt-2", companyId: "c-alfajr", title: "طلب سلفة", body: "طلب سلفة بقيمة 15,000 ر.س من خالد ناصر الشمري.", type: "REQUEST", read: false, createdAt: new Date(Date.now() - 7200000).toISOString() },
  { id: "nt-3", companyId: "c-alfajr", title: "إعلان منشور", body: "تم نشر إعلان: تحديث مواعيد الدوام في رمضان.", type: "ANNOUNCEMENT", read: true, createdAt: new Date(Date.now() - 86400000).toISOString() },
];

export const SEED_LOANS: Loan[] = [
  {
    id: "ln-1",
    companyId: "c-alfajr",
    employeeId: "e-1001",
    employeeName: "عبدالله محمد القحطاني",
    amount: 15000,
    installments: 10,
    installmentAmount: 1500,
    paidInstallments: 3,
    remaining: 10500,
    startMonth: 3,
    startYear: 2026,
    status: "ACTIVE",
    createdAt: "2026-03-01",
  },
];

export const SEED_DEDUCTIONS: Deduction[] = [
  {
    id: "dd-1",
    companyId: "c-alfajr",
    employeeId: "e-1003",
    employeeName: "خالد ناصر الشمري",
    amount: 300,
    reason: "غياب بدون إذن",
    type: "PENALTY",
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
    createdAt: today,
  },
];

export const SEED_REVIEWS: PerformanceReview[] = [
  {
    id: "pr-1",
    companyId: "c-alfajr",
    employeeId: "e-1001",
    employeeName: "عبدالله محمد القحطاني",
    cycle: "التقييم السنوي 2025",
    reviewerName: "إدارة الموارد البشرية",
    criteria: [
      { name: "جودة العمل", score: 5 },
      { name: "الالتزام والانضباط", score: 4 },
      { name: "العمل الجماعي", score: 5 },
      { name: "المبادرة والتطوير", score: 4 },
    ],
    finalRating: 4.5,
    comments: "أداء متميز خلال العام مع قيادة فعّالة للفريق.",
    status: "COMPLETED",
    createdAt: "2025-12-20",
  },
  {
    id: "pr-2",
    companyId: "c-alfajr",
    employeeId: "e-1002",
    employeeName: "سارة فهد العتيبي",
    cycle: "التقييم السنوي 2025",
    reviewerName: "إدارة الموارد البشرية",
    criteria: [
      { name: "جودة العمل", score: 4 },
      { name: "الالتزام والانضباط", score: 5 },
      { name: "العمل الجماعي", score: 4 },
      { name: "المبادرة والتطوير", score: 4 },
    ],
    finalRating: 4.25,
    status: "COMPLETED",
    createdAt: "2025-12-21",
  },
];

export const SEED_ATTENDANCE: AttendanceRecord[] = [
  { id: "at-1", companyId: "c-alfajr", employeeId: "e-1001", employeeName: "عبدالله محمد القحطاني", date: today, checkIn: "07:58", checkOut: "17:05", status: "PRESENT", lateMinutes: 0 },
  { id: "at-2", companyId: "c-alfajr", employeeId: "e-1002", employeeName: "سارة فهد العتيبي", date: today, checkIn: "08:32", checkOut: "17:00", status: "LATE", lateMinutes: 32 },
  { id: "at-3", companyId: "c-alfajr", employeeId: "e-1003", employeeName: "خالد ناصر الشمري", date: today, status: "ABSENT", lateMinutes: 0 },
  { id: "at-4", companyId: "c-noor", employeeId: "e-2001", employeeName: "ماجد سعيد الغامدي", date: today, checkIn: "08:05", checkOut: "16:40", status: "PRESENT", lateMinutes: 0 },
];

export const SEED_USERS: AppUser[] = [
  { id: "u-root", name: "أحمد العنزي", email: "admin@system.sa", role: "SUPER_ADMIN", createdAt: "2024-01-01" },
  { id: "u-sara", name: "سارة العتيبي", email: "sara@alfajr.sa", role: "HR_ADMIN", companyId: "c-alfajr", createdAt: "2024-02-12" },
  { id: "u-majed", name: "ماجد الغامدي", email: "majed@noor.sa", role: "HR_ADMIN", companyId: "c-noor", createdAt: "2024-06-02" },
];

// بيانات أولية تجريبية — تُحمَّل عند أول تشغيل ويمكن التحكم بها وتُحفظ محلياً.

export const SEED_COMPANIES: Company[] = [
  {
    id: "c-alfajr",
    name: "شركة الفجر القابضة",
    nameEn: "Al-Fajr Holding",
    city: "الرياض",
    plan: "ENTERPRISE",
    status: "ACTIVE",
    seatLimit: 500,
    subscriptionEndsAt: "2026-12-31",
    createdAt: "2024-02-10",
  },
  {
    id: "c-noor",
    name: "مؤسسة نور للتجارة",
    nameEn: "Noor Trading",
    city: "جدة",
    plan: "PRO",
    status: "ACTIVE",
    seatLimit: 120,
    subscriptionEndsAt: "2026-08-15",
    createdAt: "2024-06-01",
  },
  {
    id: "c-rawabi",
    name: "روابي الخليج للمقاولات",
    nameEn: "Rawabi Gulf Contracting",
    city: "الدمام",
    plan: "BASIC",
    status: "TRIAL",
    seatLimit: 25,
    subscriptionEndsAt: "2026-07-20",
    createdAt: "2026-06-20",
  },
];

function ev(id: string, type: Employee["events"][number]["type"], title: string, date: string, description?: string) {
  return { id, type, title, description, date };
}

export const SEED_EMPLOYEES: Employee[] = [
  {
    id: "e-1001",
    companyId: "c-alfajr",
    employeeNumber: "1001",
    displayName: "عبدالله محمد القحطاني",
    nameInEnglish: "Abdullah Al-Qahtani",
    department: "تقنية المعلومات",
    position: "مدير تطوير البرمجيات",
    nationality: "سعودي",
    idNumber: "1045xxxxxx",
    hireDate: "2019-03-01",
    status: "ACTIVE",
    employmentType: "FULL_TIME",
    baseSalary: 18000,
    housingAllowance: 4500,
    transportAllowance: 800,
    otherAllowances: 500,
    bankName: "البنك الأهلي السعودي",
    ibanNumber: "SA44 2000 0001 2345 6789 1234",
    events: [
      ev("ev1", "PERFORMANCE", "اكتمل تقييم دورة 2025 بتقييم 4.6", "2025-12-20"),
      ev("ev2", "LEAVE", "تم اعتماد إجازة سنوية لمدة 10 أيام", "2025-08-05"),
      ev("ev3", "LOAN", "تم اعتماد سلفة بقيمة 15,000 ر.س", "2025-03-12", "على 10 أقساط"),
      ev("ev4", "ATTENDANCE", "تأخر 25 دقيقة", "2025-02-18"),
    ],
  },
  {
    id: "e-1002",
    companyId: "c-alfajr",
    employeeNumber: "1002",
    displayName: "سارة فهد العتيبي",
    nameInEnglish: "Sara Al-Otaibi",
    department: "الموارد البشرية",
    position: "أخصائية موارد بشرية",
    nationality: "سعودية",
    idNumber: "1099xxxxxx",
    hireDate: "2021-09-15",
    status: "ACTIVE",
    employmentType: "FULL_TIME",
    baseSalary: 11000,
    housingAllowance: 2750,
    transportAllowance: 600,
    otherAllowances: 0,
    bankName: "مصرف الراجحي",
    ibanNumber: "SA03 8000 0000 6080 1016 7519",
    events: [
      ev("ev5", "PERFORMANCE", "اكتمل تقييم دورة 2025 بتقييم 4.2", "2025-12-21"),
      ev("ev6", "REQUEST", "تم اعتماد شهادة تعريف بالراتب", "2025-10-02"),
      ev("ev7", "LEAVE", "تم اعتماد إجازة وضع", "2025-05-01"),
    ],
  },
  {
    id: "e-1003",
    companyId: "c-alfajr",
    employeeNumber: "1003",
    displayName: "خالد ناصر الشمري",
    nameInEnglish: "Khalid Al-Shammari",
    department: "المالية",
    position: "محاسب أول",
    nationality: "سعودي",
    idNumber: "1077xxxxxx",
    hireDate: "2023-01-10",
    status: "ON_PROBATION",
    employmentType: "FULL_TIME",
    baseSalary: 9500,
    housingAllowance: 2375,
    transportAllowance: 500,
    otherAllowances: 0,
    bankName: "بنك الرياض",
    ibanNumber: "SA80 2000 0002 9876 5432 1098",
    events: [
      ev("ev8", "ATTENDANCE", "انصراف مبكر بـ 40 دقيقة", "2025-11-09"),
      ev("ev9", "REQUEST", "تم اعتماد خطاب تعريف بالعمل", "2025-09-14"),
    ],
  },
  {
    id: "e-2001",
    companyId: "c-noor",
    employeeNumber: "2001",
    displayName: "ماجد سعيد الغامدي",
    nameInEnglish: "Majed Al-Ghamdi",
    department: "المبيعات",
    position: "مدير مبيعات المنطقة الغربية",
    nationality: "سعودي",
    idNumber: "1066xxxxxx",
    hireDate: "2018-07-01",
    status: "ACTIVE",
    employmentType: "FULL_TIME",
    baseSalary: 14000,
    housingAllowance: 3500,
    transportAllowance: 1000,
    otherAllowances: 1200,
    bankName: "البنك السعودي الفرنسي",
    ibanNumber: "SA22 5500 0000 1122 3344 5566",
    events: [
      ev("ev10", "PERFORMANCE", "اكتمل تقييم دورة 2025 بتقييم 4.8", "2025-12-18"),
      ev("ev11", "LEAVE", "تم اعتماد إجازة سنوية لمدة 7 أيام", "2025-07-10"),
    ],
  },
  {
    id: "e-2002",
    companyId: "c-noor",
    employeeNumber: "2002",
    displayName: "نوف عبدالعزيز الدوسري",
    nameInEnglish: "Nouf Al-Dosari",
    department: "التسويق",
    position: "أخصائية تسويق رقمي",
    nationality: "سعودية",
    idNumber: "1088xxxxxx",
    hireDate: "2022-11-20",
    status: "ACTIVE",
    employmentType: "FULL_TIME",
    baseSalary: 8500,
    housingAllowance: 2125,
    transportAllowance: 500,
    otherAllowances: 0,
    bankName: "مصرف الراجحي",
    ibanNumber: "SA03 8000 0000 1234 9876 5432",
    events: [ev("ev12", "REQUEST", "تم اعتماد شهادة خبرة", "2025-06-30")],
  },
  {
    id: "e-3001",
    companyId: "c-rawabi",
    employeeNumber: "3001",
    displayName: "Rahul Sharma",
    nameInEnglish: "Rahul Sharma",
    department: "العمليات",
    position: "مهندس موقع",
    nationality: "هندي",
    idNumber: "2345xxxxxx",
    hireDate: "2024-04-15",
    status: "ACTIVE",
    employmentType: "CONTRACT",
    baseSalary: 7000,
    housingAllowance: 1750,
    transportAllowance: 400,
    otherAllowances: 0,
    bankName: "البنك الأهلي السعودي",
    ibanNumber: "SA44 2000 0009 8765 4321 0000",
    events: [ev("ev13", "ATTENDANCE", "تأخر 15 دقيقة", "2025-10-22")],
  },
];
