import type { AppUser, Company, Employee } from "./types";

export const SEED_USERS: AppUser[] = [
  { id: "u-root", name: "أحمد العنزي", email: "admin@system.sa", role: "SUPER_ADMIN", createdAt: "2024-01-01" },
  { id: "u-sara", name: "سارة العتيبي", email: "sara@alfajr.sa", role: "HR_ADMIN", companyId: "c-alfajr", createdAt: "2024-02-12" },
  { id: "u-majed", name: "ماجد الغامدي", email: "majed@noor.sa", role: "HR_ADMIN", companyId: "c-noor", createdAt: "2024-06-02" },
];

// بيانات أولية تجريبية — تُحمَّل عند أول تشغيل ويمكن التحكم بها وتُحفظ محلياً.

export const SEED_COMPANIES: Company[] = [
  {
    id: "c-alfajr",
    name: "شركة الفجر القابضة",
    nameEn: "Al-Fajr Holding",
    city: "الرياض",
    plan: "ENTERPRISE",
    status: "ACTIVE",
    seatLimit: 500,
    subscriptionEndsAt: "2026-12-31",
    createdAt: "2024-02-10",
  },
  {
    id: "c-noor",
    name: "مؤسسة نور للتجارة",
    nameEn: "Noor Trading",
    city: "جدة",
    plan: "PRO",
    status: "ACTIVE",
    seatLimit: 120,
    subscriptionEndsAt: "2026-08-15",
    createdAt: "2024-06-01",
  },
  {
    id: "c-rawabi",
    name: "روابي الخليج للمقاولات",
    nameEn: "Rawabi Gulf Contracting",
    city: "الدمام",
    plan: "BASIC",
    status: "TRIAL",
    seatLimit: 25,
    subscriptionEndsAt: "2026-07-20",
    createdAt: "2026-06-20",
  },
];

function ev(id: string, type: Employee["events"][number]["type"], title: string, date: string, description?: string) {
  return { id, type, title, description, date };
}

export const SEED_EMPLOYEES: Employee[] = [
  {
    id: "e-1001",
    companyId: "c-alfajr",
    employeeNumber: "1001",
    displayName: "عبدالله محمد القحطاني",
    nameInEnglish: "Abdullah Al-Qahtani",
    department: "تقنية المعلومات",
    position: "مدير تطوير البرمجيات",
    nationality: "سعودي",
    idNumber: "1045xxxxxx",
    hireDate: "2019-03-01",
    status: "ACTIVE",
    employmentType: "FULL_TIME",
    baseSalary: 18000,
    housingAllowance: 4500,
    transportAllowance: 800,
    otherAllowances: 500,
    bankName: "البنك الأهلي السعودي",
    ibanNumber: "SA44 2000 0001 2345 6789 1234",
    events: [
      ev("ev1", "PERFORMANCE", "اكتمل تقييم دورة 2025 بتقييم 4.6", "2025-12-20"),
      ev("ev2", "LEAVE", "تم اعتماد إجازة سنوية لمدة 10 أيام", "2025-08-05"),
      ev("ev3", "LOAN", "تم اعتماد سلفة بقيمة 15,000 ر.س", "2025-03-12", "على 10 أقساط"),
      ev("ev4", "ATTENDANCE", "تأخر 25 دقيقة", "2025-02-18"),
    ],
  },
  {
    id: "e-1002",
    companyId: "c-alfajr",
    employeeNumber: "1002",
    displayName: "سارة فهد العتيبي",
    nameInEnglish: "Sara Al-Otaibi",
    department: "الموارد البشرية",
    position: "أخصائية موارد بشرية",
    nationality: "سعودية",
    idNumber: "1099xxxxxx",
    hireDate: "2021-09-15",
    status: "ACTIVE",
    employmentType: "FULL_TIME",
    baseSalary: 11000,
    housingAllowance: 2750,
    transportAllowance: 600,
    otherAllowances: 0,
    bankName: "مصرف الراجحي",
    ibanNumber: "SA03 8000 0000 6080 1016 7519",
    events: [
      ev("ev5", "PERFORMANCE", "اكتمل تقييم دورة 2025 بتقييم 4.2", "2025-12-21"),
      ev("ev6", "REQUEST", "تم اعتماد شهادة تعريف بالراتب", "2025-10-02"),
      ev("ev7", "LEAVE", "تم اعتماد إجازة وضع", "2025-05-01"),
    ],
  },
  {
    id: "e-1003",
    companyId: "c-alfajr",
    employeeNumber: "1003",
    displayName: "خالد ناصر الشمري",
    nameInEnglish: "Khalid Al-Shammari",
    department: "المالية",
    position: "محاسب أول",
    nationality: "سعودي",
    idNumber: "1077xxxxxx",
    hireDate: "2023-01-10",
    status: "ON_PROBATION",
    employmentType: "FULL_TIME",
    baseSalary: 9500,
    housingAllowance: 2375,
    transportAllowance: 500,
    otherAllowances: 0,
    bankName: "بنك الرياض",
    ibanNumber: "SA80 2000 0002 9876 5432 1098",
    events: [
      ev("ev8", "ATTENDANCE", "انصراف مبكر بـ 40 دقيقة", "2025-11-09"),
      ev("ev9", "REQUEST", "تم اعتماد خطاب تعريف بالعمل", "2025-09-14"),
    ],
  },
  {
    id: "e-2001",
    companyId: "c-noor",
    employeeNumber: "2001",
    displayName: "ماجد سعيد الغامدي",
    nameInEnglish: "Majed Al-Ghamdi",
    department: "المبيعات",
    position: "مدير مبيعات المنطقة الغربية",
    nationality: "سعودي",
    idNumber: "1066xxxxxx",
    hireDate: "2018-07-01",
    status: "ACTIVE",
    employmentType: "FULL_TIME",
    baseSalary: 14000,
    housingAllowance: 3500,
    transportAllowance: 1000,
    otherAllowances: 1200,
    bankName: "البنك السعودي الفرنسي",
    ibanNumber: "SA22 5500 0000 1122 3344 5566",
    events: [
      ev("ev10", "PERFORMANCE", "اكتمل تقييم دورة 2025 بتقييم 4.8", "2025-12-18"),
      ev("ev11", "LEAVE", "تم اعتماد إجازة سنوية لمدة 7 أيام", "2025-07-10"),
    ],
  },
  {
    id: "e-2002",
    companyId: "c-noor",
    employeeNumber: "2002",
    displayName: "نوف عبدالعزيز الدوسري",
    nameInEnglish: "Nouf Al-Dosari",
    department: "التسويق",
    position: "أخصائية تسويق رقمي",
    nationality: "سعودية",
    idNumber: "1088xxxxxx",
    hireDate: "2022-11-20",
    status: "ACTIVE",
    employmentType: "FULL_TIME",
    baseSalary: 8500,
    housingAllowance: 2125,
    transportAllowance: 500,
    otherAllowances: 0,
    bankName: "مصرف الراجحي",
    ibanNumber: "SA03 8000 0000 1234 9876 5432",
    events: [ev("ev12", "REQUEST", "تم اعتماد شهادة خبرة", "2025-06-30")],
  },
  {
    id: "e-3001",
    companyId: "c-rawabi",
    employeeNumber: "3001",
    displayName: "Rahul Sharma",
    nameInEnglish: "Rahul Sharma",
    department: "العمليات",
    position: "مهندس موقع",
    nationality: "هندي",
    idNumber: "2345xxxxxx",
    hireDate: "2024-04-15",
    status: "ACTIVE",
    employmentType: "CONTRACT",
    baseSalary: 7000,
    housingAllowance: 1750,
    transportAllowance: 400,
    otherAllowances: 0,
    bankName: "البنك الأهلي السعودي",
    ibanNumber: "SA44 2000 0009 8765 4321 0000",
    events: [ev("ev13", "ATTENDANCE", "تأخر 15 دقيقة", "2025-10-22")],
  },
];
