import type { Category } from "./types";

// قائمة التصنيفات في لعبة نون عين
// gradient: تدرج لوني للبطاقة (Tailwind from-X to-Y)
// imageQuery: استعلام لجلب صور حقيقية لاحقاً من Pexels/Unsplash
export const CATEGORIES: Category[] = [
  // 🎉 ألعاب جماعية مرحة (جديد)
  {
    id: "charades",
    name: "اشرح بدون ما تتكلم",
    group: "party_games",
    icon: "🤐",
    description:
      "نمط لعب مختلف! لاعب يمثّل كلمة بدون كلام، والباقي يخمّنون.",
    hasImages: false,
    hasAudio: false,
    gameMode: "charades",
    gradient: "from-fuchsia-500 to-pink-600",
    imageQuery: "people charades party game",
    featured: true,
  },
  {
    id: "draw_guess",
    name: "ارسم وخمّن",
    group: "party_games",
    icon: "✏️",
    description:
      "لاعب يقرأ الكلمة ويرسمها، الباقي يخمّنون من الرسمة.",
    hasImages: false,
    hasAudio: false,
    gameMode: "charades",
    gradient: "from-amber-500 to-orange-600",
    imageQuery: "drawing pictionary game",
  },

  // 🎬 أفلام ومسلسلات
  {
    id: "movies_arabic",
    name: "الأفلام العربية",
    group: "movies_shows",
    icon: "🎬",
    description: "خمن الأفلام العربية الشهيرة من قديم وحديث.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-500 to-rose-700",
    imageQuery: "arabic cinema film",
  },
  {
    id: "movies_foreign",
    name: "الأفلام الأجنبية",
    group: "movies_shows",
    icon: "🎭",
    description: "أفلام هوليوود من الكلاسيكيات إلى أحدث الإصدارات.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-slate-700 to-zinc-900",
    imageQuery: "hollywood cinema movie",
  },
  {
    id: "marvel_dc",
    name: "Marvel & DC",
    group: "movies_shows",
    icon: "🦸",
    description: "أبطال خارقون، أفلام، شخصيات، وأحداث.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-600 to-blue-700",
    imageQuery: "superhero comic",
  },
  {
    id: "netflix_shows",
    name: "مسلسلات Netflix",
    group: "movies_shows",
    icon: "📺",
    description: "أشهر مسلسلات نتفليكس عبر السنين.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-600 to-black",
    imageQuery: "tv series streaming",
  },
  {
    id: "korean_shows",
    name: "مسلسلات كورية",
    group: "movies_shows",
    icon: "🇰🇷",
    description: "K-Drama من الكلاسيك إلى آخر موسم.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-pink-400 to-rose-600",
    imageQuery: "korean drama kdrama",
  },
  {
    id: "turkish_shows",
    name: "مسلسلات تركية",
    group: "movies_shows",
    icon: "🇹🇷",
    description: "أشهر المسلسلات التركية المعربة.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-600 to-red-900",
    imageQuery: "turkish drama istanbul",
  },
  {
    id: "horror_movies",
    name: "أفلام رعب",
    group: "movies_shows",
    icon: "👻",
    description: "أفلام الرعب من الكلاسيك إلى الحديث.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-zinc-800 to-black",
    imageQuery: "horror movie scary",
  },
  {
    id: "disney_pixar",
    name: "Disney & Pixar",
    group: "movies_shows",
    icon: "🏰",
    description: "أفلام ديزني وبيكسار العائلية.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-blue-500 to-purple-600",
    imageQuery: "disney castle animation",
  },

  // 🎌 أنمي ومانجا
  {
    id: "one_piece",
    name: "ون بيس",
    group: "anime_manga",
    icon: "🏴‍☠️",
    description: "كل ما يخص ون بيس: شخصيات، أركات، قوى.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-amber-500 to-red-600",
    imageQuery: "pirate ship adventure",
  },
  {
    id: "naruto",
    name: "ناروتو",
    group: "anime_manga",
    icon: "🍥",
    description: "ناروتو وشيبودن وبورتو والعالم النيني.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-orange-500 to-amber-600",
    imageQuery: "ninja japanese anime",
  },
  {
    id: "attack_on_titan",
    name: "هجوم العمالقة",
    group: "anime_manga",
    icon: "⚔️",
    description: "Attack on Titan من البداية للنهاية.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-slate-700 to-red-900",
    imageQuery: "wall fantasy fortress",
  },
  {
    id: "dragon_ball",
    name: "دراغون بول",
    group: "anime_manga",
    icon: "🐉",
    description: "Dragon Ball Z و Super و GT.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-orange-400 to-yellow-600",
    imageQuery: "dragon fantasy power",
  },
  {
    id: "demon_slayer",
    name: "قاتل الشياطين",
    group: "anime_manga",
    icon: "🗡️",
    description: "Demon Slayer / Kimetsu no Yaiba.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-emerald-600 to-slate-900",
    imageQuery: "japanese sword samurai",
  },
  {
    id: "anime_classic",
    name: "أنمي كلاسيكي",
    group: "anime_manga",
    icon: "📼",
    description: "أنميات الزمن الجميل: كونان، بوكيمون، ديجيمون.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-violet-500 to-purple-700",
    imageQuery: "retro vintage anime",
  },

  // 🎮 ألعاب فيديو
  {
    id: "minecraft",
    name: "ماين كرافت",
    group: "video_games",
    icon: "⛏️",
    description: "ماين كرافت: عوالم، وحوش، كرافت.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-emerald-500 to-green-700",
    imageQuery: "pixel block game",
  },
  {
    id: "pubg_fortnite",
    name: "PUBG & Fortnite",
    group: "video_games",
    icon: "🔫",
    description: "ألعاب الباتل رويال الشهيرة.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-orange-500 to-rose-700",
    imageQuery: "battle royale gaming",
  },
  {
    id: "fifa_ea_sports",
    name: "FIFA / EA Sports FC",
    group: "video_games",
    icon: "⚽",
    description: "كرة قدم على البلايستيشن والاكس بوكس.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-green-500 to-emerald-700",
    imageQuery: "football gaming controller",
  },
  {
    id: "call_of_duty",
    name: "كول أوف ديوتي",
    group: "video_games",
    icon: "🎯",
    description: "Call of Duty: Warzone, MW, BO.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-zinc-700 to-zinc-900",
    imageQuery: "military fps shooter",
  },
  {
    id: "resident_evil",
    name: "Resident Evil",
    group: "video_games",
    icon: "🧟",
    description: "أشهر سلسلة رعب: شخصيات، قصص، وحوش.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-emerald-800 to-red-900",
    imageQuery: "zombie horror dark",
  },
  {
    id: "gta",
    name: "GTA",
    group: "video_games",
    icon: "🚓",
    description: "Grand Theft Auto: من V لـ VI.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-purple-600 to-pink-700",
    imageQuery: "city neon night urban",
  },
  {
    id: "nintendo",
    name: "ألعاب نينتندو",
    group: "video_games",
    icon: "🍄",
    description: "ماريو، زيلدا، بوكيمون، كيربي.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-500 to-pink-600",
    imageQuery: "retro arcade game",
  },

  // ⚽ رياضة
  {
    id: "world_cup",
    name: "كأس العالم",
    group: "sports",
    icon: "🏆",
    description: "بطولات كأس العالم من 1930 لليوم.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-yellow-500 to-amber-700",
    imageQuery: "world cup trophy",
  },
  {
    id: "european_leagues",
    name: "الدوريات الأوروبية",
    group: "sports",
    icon: "🇪🇺",
    description: "بريميرليغ، لا ليغا، بوندسليغا، السيري آ.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-blue-600 to-cyan-700",
    imageQuery: "european football stadium",
  },
  {
    id: "khaleeji_leagues",
    name: "الدوريات الخليجية",
    group: "sports",
    icon: "🟢",
    description: "روشن السعودي، الكويتي، الإماراتي، القطري.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-emerald-500 to-teal-700",
    imageQuery: "football stadium night",
  },
  {
    id: "ai_player_guess",
    name: "خمن اللاعب",
    group: "sports",
    icon: "👤",
    description: "صور لاعبين بدون ملامح، خمن من هو.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-sky-500 to-blue-700",
    imageQuery: "soccer player silhouette",
  },
  {
    id: "football_ranking",
    name: "ترتيب كروي",
    group: "sports",
    icon: "📊",
    description: "رتب اللاعبين أو الأندية حسب معيار.",
    hasImages: false,
    hasAudio: false,
    gradient: "from-indigo-500 to-violet-700",
    imageQuery: "trophy ranking podium",
  },
  {
    id: "basketball_nba",
    name: "كرة السلة / NBA",
    group: "sports",
    icon: "🏀",
    description: "NBA: لاعبين، فرق، بطولات.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-orange-500 to-red-700",
    imageQuery: "basketball court NBA",
  },

  // 🚗 سيارات
  {
    id: "luxury_cars",
    name: "سيارات فاخرة",
    group: "cars",
    icon: "🚗",
    description: "رولز رويس، مرسيدس، بنتلي، فيراري.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-zinc-700 to-amber-700",
    imageQuery: "luxury car rolls royce",
  },
  {
    id: "sport_cars",
    name: "سيارات رياضية",
    group: "cars",
    icon: "🏎️",
    description: "Supercars و Hypercars الأسطورية.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-600 to-orange-700",
    imageQuery: "sports car ferrari supercar",
  },
  {
    id: "car_logos",
    name: "شعارات السيارات",
    group: "cars",
    icon: "🔰",
    description: "خمن الشركة من الشعار فقط.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-blue-700 to-zinc-800",
    imageQuery: "car logo emblem",
  },
  {
    id: "car_engine_sound",
    name: "خمن السيارة من الصوت",
    group: "cars",
    icon: "🔊",
    description: "صوت محرك، خمن نوع السيارة.",
    hasImages: false,
    hasAudio: true,
    gradient: "from-zinc-800 to-orange-700",
    imageQuery: "car engine motor",
  },

  // 🌍 ثقافة عامة
  {
    id: "countries_capitals",
    name: "بلدان وعواصم",
    group: "general_culture",
    icon: "🌐",
    description: "عواصم الدول حول العالم.",
    hasImages: false,
    hasAudio: false,
    gradient: "from-sky-500 to-blue-700",
    imageQuery: "world map globe",
  },
  {
    id: "flags",
    name: "خمن العَلَم",
    group: "general_culture",
    icon: "🏳️",
    description: "أعلام دول وخمن البلد.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-blue-500 to-emerald-600",
    imageQuery: "national flag country",
  },
  {
    id: "languages",
    name: "لغات وترجمة",
    group: "general_culture",
    icon: "🗣️",
    description: "كلمات بلغات مختلفة، خمن المعنى.",
    hasImages: false,
    hasAudio: false,
    gradient: "from-cyan-500 to-blue-700",
    imageQuery: "language books world",
  },
  {
    id: "history",
    name: "تاريخ",
    group: "general_culture",
    icon: "📜",
    description: "أحداث تاريخية شهيرة عربية وعالمية.",
    hasImages: false,
    hasAudio: false,
    gradient: "from-amber-600 to-orange-800",
    imageQuery: "ancient history civilization",
  },
  {
    id: "geography",
    name: "جغرافيا",
    group: "general_culture",
    icon: "🗺️",
    description: "جبال، أنهار، صحاري، بحار.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-teal-500 to-emerald-700",
    imageQuery: "mountain landscape nature",
  },
  {
    id: "science",
    name: "علوم",
    group: "general_culture",
    icon: "🔬",
    description: "فيزياء، كيمياء، أحياء، فضاء.",
    hasImages: false,
    hasAudio: false,
    gradient: "from-violet-500 to-indigo-700",
    imageQuery: "science laboratory experiment",
  },
  {
    id: "arab_celebs",
    name: "مشاهير عرب",
    group: "general_culture",
    icon: "🌟",
    description: "ممثلين، مغنين، رياضيين، إعلاميين عرب.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-yellow-500 to-orange-700",
    imageQuery: "arab celebrity star",
  },
  {
    id: "world_celebs",
    name: "مشاهير عالميون",
    group: "general_culture",
    icon: "✨",
    description: "نجوم هوليوود ومشاهير العالم.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-yellow-400 to-pink-600",
    imageQuery: "celebrity hollywood star",
  },

  // 🎵 صوت وصورة
  {
    id: "zoom",
    name: "زووم",
    group: "audio_visual",
    icon: "🔍",
    description: "صور مكبرة جداً، خمن الشي.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-purple-500 to-fuchsia-700",
    imageQuery: "macro zoom close-up",
  },
  {
    id: "guess_sound",
    name: "خمن الصوت",
    group: "audio_visual",
    icon: "🔉",
    description: "صوت شي، آلة، أو حيوان، خمنه.",
    hasImages: false,
    hasAudio: true,
    gradient: "from-rose-500 to-pink-700",
    imageQuery: "sound waveform audio",
  },
  {
    id: "guess_arabic_song",
    name: "خمن الأغنية العربية",
    group: "audio_visual",
    icon: "🎵",
    description: "مقطع أغنية عربية، خمن الاسم والمغني.",
    hasImages: false,
    hasAudio: true,
    gradient: "from-yellow-500 to-red-700",
    imageQuery: "arabic music concert",
  },
  {
    id: "guess_foreign_song",
    name: "خمن الأغنية الأجنبية",
    group: "audio_visual",
    icon: "🎶",
    description: "أغاني انجليزية، خمن اسمها أو مغنيها.",
    hasImages: false,
    hasAudio: true,
    gradient: "from-violet-600 to-indigo-800",
    imageQuery: "music concert stage",
  },
  {
    id: "guess_ad",
    name: "خمن الإعلان",
    group: "audio_visual",
    icon: "📺",
    description: "إعلانات شهيرة من الذاكرة.",
    hasImages: true,
    hasAudio: true,
    gradient: "from-blue-500 to-purple-700",
    imageQuery: "tv commercial advertising",
  },
  {
    id: "guess_logo",
    name: "خمن الشعار",
    group: "audio_visual",
    icon: "🏷️",
    description: "شعارات شركات وعلامات تجارية.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-amber-500 to-red-700",
    imageQuery: "brand logo company",
  },
];

export const CATEGORY_BY_ID = CATEGORIES.reduce<Record<string, Category>>(
  (acc, cat) => {
    acc[cat.id] = cat;
    return acc;
  },
  {},
);

export const CATEGORY_GROUPS = {
  party_games: { name: "ألعاب جماعية", icon: "🎉" },
  movies_shows: { name: "أفلام ومسلسلات", icon: "🎬" },
  anime_manga: { name: "أنمي ومانجا", icon: "🎌" },
  video_games: { name: "ألعاب فيديو", icon: "🎮" },
  sports: { name: "رياضة", icon: "⚽" },
  cars: { name: "سيارات", icon: "🚗" },
  general_culture: { name: "ثقافة عامة", icon: "🌍" },
  audio_visual: { name: "صوت وصورة", icon: "🎵" },
  special_daily: { name: "اليومية المميزة", icon: "✨" },
} as const;

export const CATEGORIES_PER_TEAM = 3;
