import type { Category } from "./types";

// قائمة التصنيفات في لعبة نون عين
export const CATEGORIES: Category[] = [
  // 🎬 أفلام ومسلسلات
  {
    id: "movies_arabic",
    name: "الأفلام العربية",
    group: "movies_shows",
    icon: "🎬",
    description: "خمن الأفلام العربية الشهيرة من قديم وحديث.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "movies_foreign",
    name: "الأفلام الأجنبية",
    group: "movies_shows",
    icon: "🎭",
    description: "أفلام هوليوود من الكلاسيكيات إلى أحدث الإصدارات.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "marvel_dc",
    name: "Marvel & DC",
    group: "movies_shows",
    icon: "🦸",
    description: "أبطال خارقون، أفلام، شخصيات، وأحداث.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "netflix_shows",
    name: "مسلسلات Netflix",
    group: "movies_shows",
    icon: "📺",
    description: "أشهر مسلسلات نتفليكس عبر السنين.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "korean_shows",
    name: "مسلسلات كورية",
    group: "movies_shows",
    icon: "🇰🇷",
    description: "K-Drama من الكلاسيك إلى آخر الموسم.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "turkish_shows",
    name: "مسلسلات تركية",
    group: "movies_shows",
    icon: "🇹🇷",
    description: "أشهر المسلسلات التركية المعربة.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "horror_movies",
    name: "أفلام رعب",
    group: "movies_shows",
    icon: "👻",
    description: "أفلام الرعب من الكلاسيك إلى الحديث.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "disney_pixar",
    name: "Disney & Pixar",
    group: "movies_shows",
    icon: "🏰",
    description: "أفلام ديزني وبيكسار العائلية.",
    hasImages: true,
    hasAudio: false,
  },

  // 🎌 أنمي ومانجا
  {
    id: "one_piece",
    name: "ون بيس",
    group: "anime_manga",
    icon: "🏴‍☠️",
    description: "كل ما يخص ون بيس: شخصيات، أركات، قوى.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "naruto",
    name: "ناروتو",
    group: "anime_manga",
    icon: "🍥",
    description: "ناروتو وشيبودن وبورتو والعالم النيني.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "attack_on_titan",
    name: "هجوم العمالقة",
    group: "anime_manga",
    icon: "⚔️",
    description: "Attack on Titan من البداية للنهاية.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "dragon_ball",
    name: "دراغون بول",
    group: "anime_manga",
    icon: "🐉",
    description: "Dragon Ball Z و Super و GT.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "demon_slayer",
    name: "قاتل الشياطين",
    group: "anime_manga",
    icon: "🗡️",
    description: "Demon Slayer / Kimetsu no Yaiba.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "anime_classic",
    name: "أنمي كلاسيكي",
    group: "anime_manga",
    icon: "📼",
    description: "أنميات الزمن الجميل: كونان، بوكيمون، ديجيمون.",
    hasImages: true,
    hasAudio: false,
  },

  // 🎮 ألعاب فيديو
  {
    id: "minecraft",
    name: "ماين كرافت",
    group: "video_games",
    icon: "⛏️",
    description: "ماين كرافت: عوالم، وحوش، كرافت.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "pubg_fortnite",
    name: "PUBG & Fortnite",
    group: "video_games",
    icon: "🔫",
    description: "ألعاب الباتل رويال الشهيرة.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "fifa_ea_sports",
    name: "FIFA / EA Sports FC",
    group: "video_games",
    icon: "⚽",
    description: "كرة قدم على البلايستيشن والاكس بوكس.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "call_of_duty",
    name: "كول أوف ديوتي",
    group: "video_games",
    icon: "🎯",
    description: "Call of Duty: Warzone, MW, BO.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "resident_evil",
    name: "Resident Evil",
    group: "video_games",
    icon: "🧟",
    description: "أشهر سلسلة رعب: شخصيات، قصص، وحوش.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "gta",
    name: "GTA",
    group: "video_games",
    icon: "🚓",
    description: "Grand Theft Auto: من V لـ VI.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "nintendo",
    name: "ألعاب نينتندو",
    group: "video_games",
    icon: "🍄",
    description: "ماريو، زيلدا، بوكيمون، كيربي.",
    hasImages: true,
    hasAudio: false,
  },

  // ⚽ رياضة
  {
    id: "world_cup",
    name: "كأس العالم",
    group: "sports",
    icon: "🏆",
    description: "بطولات كأس العالم من 1930 لليوم.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "european_leagues",
    name: "الدوريات الأوروبية",
    group: "sports",
    icon: "🇪🇺",
    description: "بريميرليغ، لا ليغا، بوندسليغا، السيري آ.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "khaleeji_leagues",
    name: "الدوريات الخليجية",
    group: "sports",
    icon: "🟢",
    description: "روشن السعودي، الكويتي، الإماراتي، القطري.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "ai_player_guess",
    name: "خمن اللاعب",
    group: "sports",
    icon: "👤",
    description: "صور لاعبين بدون ملامح، خمن من هو.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "football_ranking",
    name: "ترتيب كروي",
    group: "sports",
    icon: "📊",
    description: "رتب اللاعبين أو الأندية حسب معيار.",
    hasImages: false,
    hasAudio: false,
  },
  {
    id: "basketball_nba",
    name: "كرة السلة / NBA",
    group: "sports",
    icon: "🏀",
    description: "NBA: لاعبين، فرق، بطولات.",
    hasImages: true,
    hasAudio: false,
  },

  // 🚗 سيارات
  {
    id: "luxury_cars",
    name: "سيارات فاخرة",
    group: "cars",
    icon: "🚗",
    description: "رولز رويس، مرسيدس، بنتلي، فيراري.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "sport_cars",
    name: "سيارات رياضية",
    group: "cars",
    icon: "🏎️",
    description: "Supercars و Hypercars الأسطورية.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "car_logos",
    name: "شعارات السيارات",
    group: "cars",
    icon: "🔰",
    description: "خمن الشركة من الشعار فقط.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "car_engine_sound",
    name: "خمن السيارة من الصوت",
    group: "cars",
    icon: "🔊",
    description: "صوت محرك، خمن نوع السيارة.",
    hasImages: false,
    hasAudio: true,
  },

  // 🌍 ثقافة عامة
  {
    id: "countries_capitals",
    name: "بلدان وعواصم",
    group: "general_culture",
    icon: "🌐",
    description: "عواصم الدول حول العالم.",
    hasImages: false,
    hasAudio: false,
  },
  {
    id: "flags",
    name: "خمن العَلَم",
    group: "general_culture",
    icon: "🏳️",
    description: "أعلام دول وخمن البلد.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "languages",
    name: "لغات وترجمة",
    group: "general_culture",
    icon: "🗣️",
    description: "كلمات بلغات مختلفة، خمن المعنى.",
    hasImages: false,
    hasAudio: false,
  },
  {
    id: "history",
    name: "تاريخ",
    group: "general_culture",
    icon: "📜",
    description: "أحداث تاريخية شهيرة عربية وعالمية.",
    hasImages: false,
    hasAudio: false,
  },
  {
    id: "geography",
    name: "جغرافيا",
    group: "general_culture",
    icon: "🗺️",
    description: "جبال، أنهار، صحاري، بحار.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "science",
    name: "علوم",
    group: "general_culture",
    icon: "🔬",
    description: "فيزياء، كيمياء، أحياء، فضاء.",
    hasImages: false,
    hasAudio: false,
  },
  {
    id: "arab_celebs",
    name: "مشاهير عرب",
    group: "general_culture",
    icon: "🌟",
    description: "ممثلين، مغنين، رياضيين، إعلاميين عرب.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "world_celebs",
    name: "مشاهير عالميون",
    group: "general_culture",
    icon: "✨",
    description: "نجوم هوليوود ومشاهير العالم.",
    hasImages: true,
    hasAudio: false,
  },

  // 🎵 صوت وصورة
  {
    id: "zoom",
    name: "زووم",
    group: "audio_visual",
    icon: "🔍",
    description: "صور مكبرة جداً، خمن الشي.",
    hasImages: true,
    hasAudio: false,
  },
  {
    id: "guess_sound",
    name: "خمن الصوت",
    group: "audio_visual",
    icon: "🔉",
    description: "صوت شي، آلة، أو حيوان، خمنه.",
    hasImages: false,
    hasAudio: true,
  },
  {
    id: "guess_arabic_song",
    name: "خمن الأغنية العربية",
    group: "audio_visual",
    icon: "🎵",
    description: "مقطع أغنية عربية، خمن الاسم والمغني.",
    hasImages: false,
    hasAudio: true,
  },
  {
    id: "guess_foreign_song",
    name: "خمن الأغنية الأجنبية",
    group: "audio_visual",
    icon: "🎶",
    description: "أغاني انجليزية، خمن اسمها أو مغنيها.",
    hasImages: false,
    hasAudio: true,
  },
  {
    id: "guess_ad",
    name: "خمن الإعلان",
    group: "audio_visual",
    icon: "📺",
    description: "إعلانات شهيرة من الذاكرة.",
    hasImages: true,
    hasAudio: true,
  },
  {
    id: "guess_logo",
    name: "خمن الشعار",
    group: "audio_visual",
    icon: "🏷️",
    description: "شعارات شركات وعلامات تجارية.",
    hasImages: true,
    hasAudio: false,
  },
];

export const CATEGORY_BY_ID = CATEGORIES.reduce<Record<string, Category>>(
  (acc, cat) => {
    acc[cat.id] = cat;
    return acc;
  },
  {},
);

export const CATEGORY_GROUPS = {
  movies_shows: { name: "أفلام ومسلسلات", icon: "🎬" },
  anime_manga: { name: "أنمي ومانجا", icon: "🎌" },
  video_games: { name: "ألعاب فيديو", icon: "🎮" },
  sports: { name: "رياضة", icon: "⚽" },
  cars: { name: "سيارات", icon: "🚗" },
  general_culture: { name: "ثقافة عامة", icon: "🌍" },
  audio_visual: { name: "صوت وصورة", icon: "🎵" },
  special_daily: { name: "اليومية المميزة", icon: "✨" },
} as const;

export const CATEGORIES_PER_TEAM = 3;
