import type { Category } from "./types";

// قائمة التصنيفات في لعبة نون عين
// wikiTitle: اسم المقال على ويكي EN (يجلب أفضل صورة تلقائياً)
export const CATEGORIES: Category[] = [
  // 🎉 ألعاب جماعية مرحة
  {
    id: "charades",
    name: "اشرح بدون كلام",
    group: "party_games",
    icon: "🤐",
    description:
      "لاعب يشوف صورة على جواله، يمثّلها بدون كلام، والباقي يخمّنون.",
    hasImages: true,
    hasAudio: false,
    gameMode: "charades",
    gradient: "from-fuchsia-500 to-pink-600",
    wikiTitle: "Charades",
    featured: true,
  },

  // 🎬 أفلام ومسلسلات
  {
    id: "movies_arabic",
    name: "الأفلام العربية",
    group: "movies_shows",
    icon: "🎬",
    description: "أفلام عربية شهيرة من قديم وحديث.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-500 to-rose-700",
    wikiTitle: "Cinema_of_Egypt",
    wikiTitleAr: "السينما_المصرية",
  },
  {
    id: "movies_foreign",
    name: "الأفلام الأجنبية",
    group: "movies_shows",
    icon: "🎭",
    description: "أفلام هوليوود من الكلاسيك إلى الحديث.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-slate-700 to-zinc-900",
    wikiTitle: "Hollywood",
  },
  {
    id: "marvel_dc",
    name: "Marvel & DC",
    group: "movies_shows",
    icon: "🦸",
    description: "أبطال خارقون، أفلام، شخصيات.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-600 to-blue-700",
    wikiTitle: "Marvel_Cinematic_Universe",
  },
  {
    id: "netflix_shows",
    name: "مسلسلات Netflix",
    group: "movies_shows",
    icon: "📺",
    description: "أشهر مسلسلات نتفليكس عبر السنين.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-600 to-black",
    wikiTitle: "Netflix",
  },
  {
    id: "korean_shows",
    name: "مسلسلات كورية",
    group: "movies_shows",
    icon: "🇰🇷",
    description: "K-Drama من الكلاسيك إلى آخر موسم.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-pink-400 to-rose-600",
    wikiTitle: "Korean_drama",
  },
  {
    id: "turkish_shows",
    name: "مسلسلات تركية",
    group: "movies_shows",
    icon: "🇹🇷",
    description: "أشهر المسلسلات التركية المعربة.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-600 to-red-900",
    wikiTitle: "Turkish_television_drama",
  },
  {
    id: "horror_movies",
    name: "أفلام رعب",
    group: "movies_shows",
    icon: "👻",
    description: "أفلام الرعب من الكلاسيك إلى الحديث.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-zinc-800 to-black",
    wikiTitle: "Horror_film",
  },
  {
    id: "disney_pixar",
    name: "Disney & Pixar",
    group: "movies_shows",
    icon: "🏰",
    description: "أفلام ديزني وبيكسار العائلية.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-blue-500 to-purple-600",
    wikiTitle: "Walt_Disney_Pictures",
  },

  // 🎌 أنمي ومانجا
  {
    id: "one_piece",
    name: "ون بيس",
    group: "anime_manga",
    icon: "🏴‍☠️",
    description: "ون بيس: شخصيات، أركات، قوى.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-amber-500 to-red-600",
    wikiTitle: "One_Piece",
  },
  {
    id: "naruto",
    name: "ناروتو",
    group: "anime_manga",
    icon: "🍥",
    description: "ناروتو وشيبودن وبورتو.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-orange-500 to-amber-600",
    wikiTitle: "Naruto",
  },
  {
    id: "attack_on_titan",
    name: "هجوم العمالقة",
    group: "anime_manga",
    icon: "⚔️",
    description: "Attack on Titan من البداية للنهاية.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-slate-700 to-red-900",
    wikiTitle: "Attack_on_Titan",
  },
  {
    id: "dragon_ball",
    name: "دراغون بول",
    group: "anime_manga",
    icon: "🐉",
    description: "Dragon Ball Z و Super.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-orange-400 to-yellow-600",
    wikiTitle: "Dragon_Ball",
  },
  {
    id: "demon_slayer",
    name: "قاتل الشياطين",
    group: "anime_manga",
    icon: "🗡️",
    description: "Demon Slayer / Kimetsu no Yaiba.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-emerald-600 to-slate-900",
    wikiTitle: "Demon_Slayer:_Kimetsu_no_Yaiba",
  },
  {
    id: "anime_classic",
    name: "أنمي كلاسيكي",
    group: "anime_manga",
    icon: "📼",
    description: "كونان، بوكيمون، ديجيمون.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-violet-500 to-purple-700",
    wikiTitle: "Detective_Conan",
  },

  // 🎮 ألعاب فيديو
  {
    id: "minecraft",
    name: "ماين كرافت",
    group: "video_games",
    icon: "⛏️",
    description: "Minecraft: عوالم، وحوش، كرافت.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-emerald-500 to-green-700",
    wikiTitle: "Minecraft",
  },
  {
    id: "pubg_fortnite",
    name: "PUBG & Fortnite",
    group: "video_games",
    icon: "🔫",
    description: "ألعاب الباتل رويال الشهيرة.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-orange-500 to-rose-700",
    wikiTitle: "PUBG:_Battlegrounds",
  },
  {
    id: "fifa_ea_sports",
    name: "FIFA / EA FC",
    group: "video_games",
    icon: "⚽",
    description: "كرة قدم على البلايستيشن والاكس بوكس.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-green-500 to-emerald-700",
    wikiTitle: "EA_Sports_FC",
  },
  {
    id: "call_of_duty",
    name: "كول أوف ديوتي",
    group: "video_games",
    icon: "🎯",
    description: "Call of Duty: Warzone, MW, BO.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-zinc-700 to-zinc-900",
    wikiTitle: "Call_of_Duty",
  },
  {
    id: "resident_evil",
    name: "Resident Evil",
    group: "video_games",
    icon: "🧟",
    description: "أشهر سلسلة رعب.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-emerald-800 to-red-900",
    wikiTitle: "Resident_Evil",
  },
  {
    id: "gta",
    name: "GTA",
    group: "video_games",
    icon: "🚓",
    description: "Grand Theft Auto: من V لـ VI.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-purple-600 to-pink-700",
    wikiTitle: "Grand_Theft_Auto",
  },
  {
    id: "nintendo",
    name: "ألعاب نينتندو",
    group: "video_games",
    icon: "🍄",
    description: "ماريو، زيلدا، بوكيمون.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-500 to-pink-600",
    wikiTitle: "Super_Mario",
  },

  // ⚽ رياضة
  {
    id: "world_cup",
    name: "كأس العالم",
    group: "sports",
    icon: "🏆",
    description: "بطولات كأس العالم من 1930 لليوم.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-yellow-500 to-amber-700",
    wikiTitle: "FIFA_World_Cup",
  },
  {
    id: "european_leagues",
    name: "الدوريات الأوروبية",
    group: "sports",
    icon: "🇪🇺",
    description: "بريميرليغ، لا ليغا، بوندسليغا.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-blue-600 to-cyan-700",
    wikiTitle: "Premier_League",
  },
  {
    id: "khaleeji_leagues",
    name: "الدوريات الخليجية",
    group: "sports",
    icon: "🟢",
    description: "روشن السعودي، الكويتي، الإماراتي.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-emerald-500 to-teal-700",
    wikiTitle: "Saudi_Pro_League",
  },
  {
    id: "ai_player_guess",
    name: "خمن اللاعب",
    group: "sports",
    icon: "👤",
    description: "أوصاف لاعبين شهيرين.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-sky-500 to-blue-700",
    wikiTitle: "Cristiano_Ronaldo",
  },
  {
    id: "football_ranking",
    name: "ترتيب كروي",
    group: "sports",
    icon: "📊",
    description: "رتب اللاعبين أو الأندية حسب معيار.",
    hasImages: false,
    hasAudio: false,
    gradient: "from-indigo-500 to-violet-700",
    wikiTitle: "Ballon_d%27Or",
  },
  {
    id: "basketball_nba",
    name: "كرة السلة / NBA",
    group: "sports",
    icon: "🏀",
    description: "NBA: لاعبين، فرق، بطولات.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-orange-500 to-red-700",
    wikiTitle: "National_Basketball_Association",
  },

  // 🚗 سيارات
  {
    id: "luxury_cars",
    name: "سيارات فاخرة",
    group: "cars",
    icon: "🚗",
    description: "رولز رويس، مرسيدس، بنتلي.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-zinc-700 to-amber-700",
    wikiTitle: "Rolls-Royce_Phantom",
  },
  {
    id: "sport_cars",
    name: "سيارات رياضية",
    group: "cars",
    icon: "🏎️",
    description: "Supercars و Hypercars الأسطورية.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-red-600 to-orange-700",
    wikiTitle: "Bugatti_Chiron",
  },
  {
    id: "car_logos",
    name: "شعارات السيارات",
    group: "cars",
    icon: "🔰",
    description: "خمّن الشركة من الشعار.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-blue-700 to-zinc-800",
    wikiTitle: "BMW",
  },
  {
    id: "car_engine_sound",
    name: "خمن السيارة من الصوت",
    group: "cars",
    icon: "🔊",
    description: "صوت محرك، خمّن نوع السيارة.",
    hasImages: false,
    hasAudio: true,
    gradient: "from-zinc-800 to-orange-700",
    wikiTitle: "Lamborghini",
  },

  // 🌍 ثقافة عامة
  {
    id: "countries_capitals",
    name: "بلدان وعواصم",
    group: "general_culture",
    icon: "🌐",
    description: "عواصم الدول حول العالم.",
    hasImages: false,
    hasAudio: false,
    gradient: "from-sky-500 to-blue-700",
    wikiTitle: "World_map",
  },
  {
    id: "flags",
    name: "خمن العَلَم",
    group: "general_culture",
    icon: "🏳️",
    description: "أعلام دول.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-blue-500 to-emerald-600",
    wikiTitle: "Flag",
  },
  {
    id: "languages",
    name: "لغات وترجمة",
    group: "general_culture",
    icon: "🗣️",
    description: "كلمات بلغات مختلفة.",
    hasImages: false,
    hasAudio: false,
    gradient: "from-cyan-500 to-blue-700",
    wikiTitle: "List_of_languages_by_number_of_native_speakers",
  },
  {
    id: "history",
    name: "تاريخ",
    group: "general_culture",
    icon: "📜",
    description: "أحداث تاريخية شهيرة.",
    hasImages: false,
    hasAudio: false,
    gradient: "from-amber-600 to-orange-800",
    wikiTitle: "Pyramid_of_Khufu",
  },
  {
    id: "geography",
    name: "جغرافيا",
    group: "general_culture",
    icon: "🗺️",
    description: "جبال، أنهار، صحاري.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-teal-500 to-emerald-700",
    wikiTitle: "Mount_Everest",
  },
  {
    id: "science",
    name: "علوم",
    group: "general_culture",
    icon: "🔬",
    description: "فيزياء، كيمياء، أحياء، فضاء.",
    hasImages: false,
    hasAudio: false,
    gradient: "from-violet-500 to-indigo-700",
    wikiTitle: "Science",
  },
  {
    id: "arab_celebs",
    name: "مشاهير عرب",
    group: "general_culture",
    icon: "🌟",
    description: "ممثلين ومغنين عرب.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-yellow-500 to-orange-700",
    wikiTitleAr: "محمد_عبده_(مغني)",
    wikiTitle: "Mohammed_Abdu",
  },
  {
    id: "world_celebs",
    name: "مشاهير عالميون",
    group: "general_culture",
    icon: "✨",
    description: "نجوم هوليوود ومشاهير العالم.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-yellow-400 to-pink-600",
    wikiTitle: "Hollywood_Walk_of_Fame",
  },

  // 🎵 صوت وصورة
  {
    id: "zoom",
    name: "زووم",
    group: "audio_visual",
    icon: "🔍",
    description: "صور مكبرة جداً.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-purple-500 to-fuchsia-700",
    wikiTitle: "Macro_photography",
  },
  {
    id: "guess_sound",
    name: "خمن الصوت",
    group: "audio_visual",
    icon: "🔉",
    description: "صوت شي أو حيوان.",
    hasImages: false,
    hasAudio: true,
    gradient: "from-rose-500 to-pink-700",
    wikiTitle: "Sound",
  },
  {
    id: "guess_arabic_song",
    name: "خمن الأغنية العربية",
    group: "audio_visual",
    icon: "🎵",
    description: "مقطع أغنية عربية.",
    hasImages: false,
    hasAudio: true,
    gradient: "from-yellow-500 to-red-700",
    wikiTitle: "Umm_Kulthum",
  },
  {
    id: "guess_foreign_song",
    name: "خمن الأغنية الأجنبية",
    group: "audio_visual",
    icon: "🎶",
    description: "أغاني انجليزية.",
    hasImages: false,
    hasAudio: true,
    gradient: "from-violet-600 to-indigo-800",
    wikiTitle: "Michael_Jackson",
  },
  {
    id: "guess_ad",
    name: "خمن الإعلان",
    group: "audio_visual",
    icon: "📺",
    description: "إعلانات شهيرة من الذاكرة.",
    hasImages: true,
    hasAudio: true,
    gradient: "from-blue-500 to-purple-700",
    wikiTitle: "Television_advertisement",
  },
  {
    id: "guess_logo",
    name: "خمن الشعار",
    group: "audio_visual",
    icon: "🏷️",
    description: "شعارات شركات شهيرة.",
    hasImages: true,
    hasAudio: false,
    gradient: "from-amber-500 to-red-700",
    wikiTitle: "Logo",
  },
];

export const CATEGORY_BY_ID = CATEGORIES.reduce<Record<string, Category>>(
  (acc, cat) => {
    acc[cat.id] = cat;
    return acc;
  },
  {},
);

export const CATEGORY_GROUPS = {
  party_games: { name: "ألعاب جماعية", icon: "🎉" },
  movies_shows: { name: "أفلام ومسلسلات", icon: "🎬" },
  anime_manga: { name: "أنمي ومانجا", icon: "🎌" },
  video_games: { name: "ألعاب فيديو", icon: "🎮" },
  sports: { name: "رياضة", icon: "⚽" },
  cars: { name: "سيارات", icon: "🚗" },
  general_culture: { name: "ثقافة عامة", icon: "🌍" },
  audio_visual: { name: "صوت وصورة", icon: "🎵" },
  special_daily: { name: "اليومية المميزة", icon: "✨" },
} as const;

export const CATEGORIES_PER_TEAM = 3;
