import type { TopicId } from "./types";

/**
 * Knowledge Base — concise notes for each topic, derived directly from the
 * course slides (Lovelock & Wirtz, Services Marketing 7/e — Chapters 4, 7, 8,
 * 10, 11) provided by the student.
 *
 * This serves as the retrieval source ("RAG context") for the AI features.
 * When the AI generates questions, explanations or analysis it is instructed
 * to rely ONLY on this content, which keeps everything within the course
 * material and prevents hallucination.
 */
export const KNOWLEDGE_BASE: Record<TopicId, string> = {
  // ───────────────────────── Chapter 4 ─────────────────────────
  "flower-of-service":
    "A service product comprises the core product (the central component supplying the principal, problem-solving benefits customers seek), supplementary services, and delivery processes. The Flower of Service shows the core at the centre surrounded by eight petals of supplementary services. The eight clusters are classified as either facilitating or enhancing. In a well-managed organization the petals and core are 'fresh and well-formed'; market positioning strategy helps determine which supplementary services to include. The four facilitating petals are Information, Order-Taking, Billing and Payment; the four enhancing petals are Consultation, Hospitality, Safekeeping and Exceptions.",
  "facilitating-services":
    "Facilitating supplementary services are either needed for service delivery or help in the use of the core product. They are: INFORMATION (directions to service site, schedules/service hours, prices, reminders, warnings, conditions of sale, notification of changes, documentation, confirmation of reservations, account summaries, receipts and tickets); ORDER-TAKING (applications such as memberships and subscriptions and prerequisite-based services; order entry; reservations and check-in for seats, tables, rooms, rentals, appointments); BILLING (periodic statements, invoices for transactions, verbal statements of amount due, self-billing, machine display of amount due); PAYMENT (self-service such as inserting card/cash or electronic funds transfer; direct to payee or intermediary such as cash/check/card handling and coupon redemption; automatic deduction from financial deposits).",
  "enhancing-services":
    "Enhancing supplementary services add extra value for the customer. They are: CONSULTATION (customized advice, personal counseling, tutoring/training in product use, management or technical consulting) — unlike Information, which is a simple response to questions, consultation involves a dialogue to probe customer requirements and develop a tailored solution; HOSPITALITY (greeting, food and beverages, toilets/washrooms, waiting facilities and amenities such as lounges and weather protection, magazines/entertainment, transport, security) — ideally reflecting pleasure at meeting new customers and greeting returning ones; SAFEKEEPING (caring for possessions customers bring: child/pet care, parking and valet, coat rooms, baggage handling, storage, safe deposit boxes, security personnel; and caring for goods purchased/rented: packaging, pickup, delivery, installation, inspection, cleaning, refueling, maintenance, repair); EXCEPTIONS (supplementary services that fall outside the routine: special requests in advance such as children's/dietary/medical/religious needs; handling complaints, compliments and suggestions; problem solving including warranties and guarantees; restitution such as refunds, compensation and free repair).",
  "branding-alternatives":
    "A spectrum of branding alternatives exists for services, running from corporate branding to individual product branding (derived from Aaker and Joachimsthaler): BRANDED HOUSE — a single brand covers all products and services (e.g., Virgin Group; also FedEx); SUBBRANDS — a master brand with distinct sub-brands (e.g., Raffles Class at Singapore Airlines; British Airways offers seven distinct air travel products such as First, Club World, World Traveller Plus, World Traveller, Club Europe, Euro-Traveller, Shuttle); ENDORSED BRANDS — the product brand is primary, endorsed by the corporate brand (e.g., Starwood Hotels & Resorts; Courtyard by Marriott; Ritz-Carlton); HOUSE OF BRANDS — separate, stand-alone, often unrelated brands (e.g., Yum! Brands; P&G). Branding can be employed at corporate level (easily recognized, holds meaning, stands for a way of doing business) and product level (communicates distinctive experiences and benefits of a specific service concept). The brand promise/value proposition is the heart and soul of the brand, not just a tag line or logo.",
  "new-service-development":
    "There are seven categories of new services in a hierarchy from simple to radical: STYLE CHANGES (visible changes in service design or scripts, e.g., repainting, new uniforms — the most modest); SERVICE IMPROVEMENTS (modest changes in performance of current products); SUPPLEMENTARY SERVICE INNOVATIONS (adding new or improved facilitating or enhancing elements); PROCESS-LINE EXTENSIONS (alternative delivery procedures, e.g., telephone- or internet-based banking); PRODUCT LINE EXTENSIONS (additions to current product lines); MAJOR PROCESS INNOVATIONS (using new processes to deliver existing products with added benefits); MAJOR SERVICE INNOVATIONS (new core products for previously undefined markets — the most radical). In new services the core product is often of secondary importance — many innovations are in supplementary services or delivery. Success factors include market synergy (good fit with firm image, advantage in meeting needs, strong support), organizational factors (inter-functional cooperation, internal marketing to educate staff) and market research factors (scientific studies early, well-defined concept). Market knowledge is of utmost importance.",
  "marketing-communications":
    "Marketing communications (the 'Promotion & Education' element of the 7Ps) explain and promote the firm's value proposition; they are more than advertising (also PR, personal selling, etc.). Six specific roles: (1) position and differentiate the service; (2) help customers evaluate offerings and highlight differences that matter; (3) promote the contribution of personnel and backstage operations; (4) add value through communication content (information and consultation); (5) facilitate customer involvement in production (e.g., training customers, showing service delivery in action); (6) stimulate or dampen demand to match capacity. Educational/promotional objectives include building awareness, reducing perceived risk, teaching customers how to use the service, encouraging trial, and recognizing valued customers.",
  "5ws-model":
    "The '5 Ws' model is a checklist for marketing communications planning: WHO is our target audience? WHAT do we need to communicate and achieve? HOW should we communicate this? WHERE should we communicate this? WHEN do communications need to take place? The target audience falls into three broad categories: prospects (reached via the traditional communication mix because they are not known in advance), users (reached via more cost-effective channels), and employees (a secondary audience whose behavior is shaped via internal marketing using company-specific channels).",
  "word-of-mouth":
    "Word of mouth (WOM) consists of messages originating from outside the organization; recommendations from other customers are viewed as more credible. Strategies to stimulate positive WOM: create exciting promotions that get people talking; offer promotions that encourage customers to persuade others (e.g., 'bring two friends, and the third eats for free'); develop referral incentive schemes (free service unit, voucher or cash for introducing new customers); reference other purchasers and knowledgeable individuals; present and publicize testimonials (ads and brochures featuring satisfied customers). New types of online WOM include blogs and Twitter, plus media coverage that compares offerings and advises on 'best buys'.",
  "corporate-design":
    "Corporate design strategies are part and parcel of the communications mix. Many service firms employ a unified and distinctive visual appearance for all tangible elements (logos, uniforms, physical facilities) to provide a recognizable theme linking all operations through physical evidence — e.g., BP's bright green and yellow service stations; McDonald's 'Golden Arches' (a trademarked symbol used as the primary logo with the name secondary). International companies must select designs carefully to avoid culturally inappropriate messages; easily recognizable symbols matter where the local language is not in Roman script or where many people are illiterate. FedEx created a 'family of companies' of subbrands (Express, Ground, Home Delivery, Freight, etc.), each with a different color scheme for the second word (Express is red/orange, Ground is green).",

  // ───────────────────────── Chapter 8 ─────────────────────────
  blueprinting:
    "Blueprinting is the key tool used to design new services or redesign existing ones — a more complex version of flowcharting. A flowchart describes an existing process, often in a simple form; a blueprint specifies in detail how a service process is constructed, including everything visible to the customer and where potential fail points lie. To develop a blueprint, identify the key activities in creating and delivering the service and define the 'big picture' before drilling down to detail. Advantages: distinguishes front-stage from back-stage; clarifies interactions and the support of backstage activities/systems; identifies potential fail points so preventive measures and contingencies can be prepared; pinpoints stages where customers wait; and helps develop standards for maximum customer waiting time. The blueprint complements service scripts.",
  flowcharting:
    "Flowcharting is a technique for displaying the nature and sequence of the different steps in delivering service to customers. It helps clarify product elements and provides a way of understanding the total customer service experience. It shows how the nature of customer involvement with service organizations differs by service type — people processing, possession processing, mental-stimulus processing, and information processing. The first two involve physical processes and the last two are information-based. A flowchart describes an existing process in a simple form, whereas a blueprint adds detail such as the line of visibility, fail points and standards.",
  "service-blueprint":
    "A service blueprint can be illustrated with the 'service drama' of a restaurant in three acts. ACT 1 (prologue and introductory scenes): the customer makes a reservation by phone, arrives, has the car parked by a valet, leaves coats in the coat room, and enjoys a drink at the bar while waiting; below the line of visibility the blueprint specifies actions to ensure each front-stage step meets expectations (recording reservations, handling coats, maintaining facilities/equipment, training and assigning staff). ACT 2 (delivery of the core product): cocktails, seating, ordering food and wine, wine service — potential fail points include incomplete/unclear menu information and items not actually available; errors in transmitting information are a common cause of quality failure; customers judge not just food quality but how quickly it is served. ACT 3 (the drama concludes): remaining actions must move quickly and smoothly with no surprises — customers expect an accurate, clear, prompt bill, payment handled politely, and thanks for their patronage.",
  "fail-proofing":
    "Failure analysis of service processes reveals fail-proofing opportunities to reduce or eliminate future errors. Fail-safe (poka-yoke) methods are needed for both employees and customers. From the customer's perspective, the most serious fail points are those that prevent customers from reaching or enjoying the core product — e.g., in a restaurant, reservations (can the customer get through by phone? was a table available at the requested time/date? was the reservation recorded accurately?) and seating (was the table available when promised?). Once fail points are identified, a careful root-cause analysis of failures in the service processes is essential.",
  "service-standards":
    "Service providers set standards for each step high enough to satisfy and even delight customers. Standards should include time parameters, scripts and prescriptions for appropriate style and behavior, and must be expressed in ways that allow objective measurement. Performance targets a specific process and team performance goals for which employees are accountable (e.g., process 80% of orders within 24 hours). Evaluation distinguishes between standards and goals. The first impression is important and affects customers' quality evaluations during later stages, because perceptions of service experiences tend to be cumulative; for a low-contact service a single failure committed front-stage is relatively more serious than for a high-contact service.",
  ssts:
    "Self-service technologies (SSTs) are the ultimate form of customer involvement, where customers undertake specific activities using facilities or systems provided by the service provider; the customer's time and effort replace those of employees. Advantages: convenience, 24/7 access, fast completion of transactions. Disadvantages: anxiety and stress for some customers, loss of the social experience, and technical problems (system down, forgotten passwords). Keys to SST success: firms must ensure systems are reliable and easy to use; the SST must be better than the personal alternatives for customers to accept it; and firms must provide systems for immediate service recovery when the technology fails. Marketing communications can push customers toward change by preparing them, explaining the rationale and benefits, and clarifying what to do differently.",

  // ───────────────────────── Chapter 10 ─────────────────────────
  servicescape:
    "The service environment (servicescape) has four purposes: shape customers' experience and behaviors; support image, positioning and differentiation; form part of the value proposition; and facilitate the service encounter and enhance productivity. The environment influences buyer behavior in three ways: as a message-creating medium (symbolic cues communicating the distinctive nature and quality of the experience), an attention-creating medium (making the service stand out from competitors), and an effect-creating medium (using colors, textures, sounds, scents and spatial design to enhance the desired experience). The Servicescape Model identifies the key dimensions, viewed holistically: internal responses (cognitive — perceptions/beliefs of quality; emotional — feelings/moods; psychological — pain/comfort) lead to behavioral responses such as avoiding a crowded store or staying longer and spending more in a comfortable one. The key to effective design is how well each dimension fits with everything else. The three core dimensions are ambient conditions; spatial layout and functionality; and signs, symbols and artifacts.",
  "ambient-conditions":
    "Ambient conditions relate to the five senses and include lighting and color, temperature and scent, and sounds, noise and music. Intelligent design of these conditions produces desired behavioral responses. MUSIC has a powerful effect even at barely audible levels; fast tempo and loud music raise arousal, people tend to adjust their pace to the rhythm, and careful selection can deter the 'wrong' kind of customer. SCENT — an ambient scent pervades the environment without relating to a particular product; scents affect mood, evaluation and even purchase (aromatherapy induces emotional and physiological responses). COLOR is defined in three dimensions — hue (the shade, e.g., red or blue), value (brightness/darkness) and chroma (intensity/saturation); warm colors encourage fast decision making (good for impulse purchases) while cool colors are preferred for high-involvement decisions.",
  "pleasure-arousal":
    "Russell's Model of Affect explains feelings and their behavioral effects along two main dimensions: PLEASURE (subjective — how much the individual likes or dislikes the environment) and AROUSAL (how stimulated the person feels, depending on the 'information load' of the environment, from deep sleep to highest activity). The advantage is a simple, direct approach that lets firms set goals for emotional states (e.g., a spa wanting customers to feel relaxed). Behavioral outcomes: pleasant environments lead to approach, unpleasant ones to avoidance; arousal amplifies the effect — pleasant + increased arousal yields a stronger positive response, while unpleasant + increased arousal makes people feel distressed. Emotions during service encounters are an important driver of customer loyalty.",
  "mehrabian-russell":
    "The Mehrabian-Russell Stimulus-Response Model holds that our feelings are central to how we respond to environmental stimuli: the environment and its conscious and unconscious perceptions affect how people feel, and feelings (not just perceptions or thoughts) drive behavior. The outcomes are either approach or avoidance of the environment, along with other outcomes such as the amount spent and satisfaction. Affect is itself driven by perceptions and cognitive processes — the more complex the cognitive process, the greater its potential effect on feelings.",

  // ───────────────────────── Chapter 11 ─────────────────────────
  "role-stress":
    "Frontline employees perform boundary-spanning roles and experience role stress from three main sources: (1) organization versus client — the dilemma of following company rules or meeting customer requests; (2) person versus role — conflict between job requirements and the employee's own personality and beliefs; (3) client versus client — conflicts between customers that require employee intervention. Management's many (sometimes conflicting) expectations of frontline staff add to this stress: delight customers, be fast and efficient, cross-sell and up-sell, and enforce pricing schedules.",
  "boundary-spanners":
    "Service employees are crucially important: from the customer's perspective the encounter with service staff is the most important aspect of the service, and from the firm's perspective the front line is an important source of differentiation and competitive advantage and a driver of customer loyalty (by anticipating needs, customizing service and building relationships). Frontline employees are boundary spanners who link the organization to the outside world; even in low-contact services where many transactions are automated (ATM, IVR, websites) they remain important, and occasional encounters are 'moments of truth' that shape customer perceptions. Boundary spanners must pursue both operational and marketing goals simultaneously, which exposes them to role conflict and stress.",
  empowerment:
    "Empowerment is appropriate when the business strategy is based on customization and differentiation, long-term relationships, and complex technologies. The involvement model distributes information, knowledge, power and rewards throughout the organization. There are levels of involvement: suggestion involvement, job involvement, and high involvement (including profit sharing). Empowerment forms part of training/enabling frontline staff so they can deliver good service; it contrasts with a standardized 'production-line' approach.",
  "service-culture":
    "Leadership and a service culture underpin service advantage. Charismatic/transformational leadership changes employees' values to align with the firm and motivates them to perform better. A service culture consists of shared perceptions and values about what is important; a strong culture focuses the whole organization on the front line. The inverted organizational pyramid places the front line at the top, supported by management. Service culture is built and reinforced through leadership, internal communications and HR practices.",
  "internal-marketing":
    "Internal marketing is essential in large service businesses: it ensures effective service delivery, achieves harmonious working relationships, and builds employee trust and loyalty. It supports the Service Talent Cycle — hiring the right people (competing for 'talent market share', being a preferred employer, using structured interviews, observing behavior since past behavior predicts the future, personality tests and realistic job previews), training service employees (organizational culture/purpose/strategy, interpersonal and technical skills, product/service knowledge), empowering them, building high-performance teams, and motivating and energizing staff through effective rewards (job content, feedback and recognition, and goal accomplishment).",
  "cycle-of-success":
    "The Cycle of Success reflects a long-term view with investment in people: attractive wages and benefits and intensive training. Employees are happier and deliver higher-quality service, and customers remain loyal because they appreciate the continuity and quality. It contrasts with the Cycle of Failure (built on cost minimization) and the Cycle of Mediocrity (found in large bureaucratic organizations where service is standardized, promotions rest on seniority, and success is measured by the absence of mistakes, so customers have little incentive to cooperate).",
  "cycle-of-failure":
    "The Cycle of Failure has two interlocking loops. The EMPLOYEE cycle: narrow job design, an emphasis on rules, boredom, weak (poor) service response, and high employee turnover. The CUSTOMER cycle: customer dissatisfaction, constantly dealing with new/unfamiliar faces, and rapid customer turnover. Its neglected costs include continual recruiting and training costs, lower productivity, and the cost of constantly winning new customers. A related problem is service sabotage — covert or overt, routine or intermittent behaviors such as deliberately slowing service or treating guests rudely.",
  "emotional-labor":
    "Emotional labor is the act of expressing socially desired emotions during service transactions. Performing it can cause stress and strain for employees; good human-resource practices help alleviate this strain through selective hiring and training. It arises because frontline (boundary-spanning) staff must display the feelings the job requires regardless of how they actually feel.",
};

/** Build a compact context block for the AI given a set of topics. */
export function buildContext(topics: TopicId[]): string {
  const seen = new Set<TopicId>();
  const lines: string[] = [];
  for (const t of topics) {
    if (seen.has(t)) continue;
    seen.add(t);
    if (KNOWLEDGE_BASE[t]) {
      lines.push(`### ${t}\n${KNOWLEDGE_BASE[t]}`);
    }
  }
  return lines.join("\n\n");
}
