import type { Bilingual, Chapter, Question } from "../types";
import type { Subject, SubjectTopic } from "./services-marketing";
import { COMPENSATION_MANAGEMENT_ESSAYS } from "../essays/compensation-management";

/* ───────────────────────────── Topics ───────────────────────────── */

const T = (id: string, en: string, ar: string, chapter: Chapter): SubjectTopic => ({
  id,
  label: { en, ar },
  chapter,
});

const topics: Record<string, SubjectTopic> = {
  // Ch 1 — The Pay Model
  "comp-matters": T("comp-matters", "Why Compensation Matters", "أهمية التعويضات", 1),
  "pay-stakeholders": T("pay-stakeholders", "Stakeholder Perspectives", "وجهات نظر أصحاب المصلحة", 1),
  "pay-behavior": T("pay-behavior", "How Pay Influences Behavior", "كيف يؤثر الأجر على السلوك", 1),
  "forms-of-pay": T("forms-of-pay", "Forms of Pay", "أشكال الأجر", 1),
  "pay-model": T("pay-model", "The Pay Model (Objectives & Policies)", "نموذج الأجر (الأهداف والسياسات)", 1),
  // Ch 7 — Defining Competitiveness
  "external-competitiveness": T("external-competitiveness", "External Competitiveness", "التنافسية الخارجية", 7),
  "labor-market": T("labor-market", "Labor Market Factors", "عوامل سوق العمل", 7),
  "labor-theories": T("labor-theories", "Labor Market Theories", "نظريات سوق العمل", 7),
  "product-market": T("product-market", "Product Market & Ability to Pay", "سوق المنتج والقدرة على الدفع", 7),
  "pay-policies": T("pay-policies", "Competitive Pay Policies", "سياسات الأجر التنافسية", 7),
  // Ch 12 — Benefit Determination
  "benefits-growth": T("benefits-growth", "Growth in Benefits", "نمو المزايا", 12),
  "benefits-value": T("benefits-value", "Value & Planning", "القيمة والتخطيط", 12),
  "flexible-benefits": T("flexible-benefits", "Flexible Benefit Programs", "برامج المزايا المرنة", 12),
  "benefits-financing": T("benefits-financing", "Financing & Administration", "التمويل والإدارة", 12),
  // Ch 13 — Benefit Options
  "legally-required": T("legally-required", "Legally Required Benefits", "المزايا الإلزامية قانوناً", 13),
  "retirement-plans": T("retirement-plans", "Retirement & Savings Plans", "خطط التقاعد والادخار", 13),
  "insurance-benefits": T("insurance-benefits", "Life & Disability Insurance", "تأمين الحياة والعجز", 13),
  "health-care": T("health-care", "Medical & Health Care", "الرعاية الطبية والصحية", 13),
  // Ch 16 — International Pay
  "intl-factors": T("intl-factors", "Factors Affecting International Pay", "عوامل الأجر الدولي", 16),
  "social-contract": T("social-contract", "Social Contracts & Regulation", "العقد الاجتماعي والتنظيم", 16),
  "japan-germany": T("japan-germany", "Japanese & German Systems", "النظامان الياباني والألماني", 16),
  "global-mindset": T("global-mindset", "Strategic Market Mind-Set", "العقلية الاستراتيجية للسوق", 16),
  "expatriate-pay": T("expatriate-pay", "Expatriate Compensation", "تعويضات المغتربين", 16),
};

/* ─────────────────────────── Knowledge base ───────────────────────────
   English notes — used to teach: Study Mode, Chapter Summaries and Flashcards
   read these, and they ground the AI tutor strictly to course content. */

const knowledge: Record<string, string> = {
  "comp-matters":
    "Compensation matters because labor costs affect efficiency, quality and customer service. Successful companies balance higher pay with higher productivity. Pay influences employee behavior, which directly impacts organizational success — so compensation is both a major cost to manage and a strategic tool.",
  "pay-stakeholders":
    "Different stakeholders view compensation differently. SOCIETY sees it as a measure of justice/equity (e.g., male/female earning differentials); the private sector spends about 42 cents on benefits for every dollar of wages. STOCKHOLDERS focus on executive pay and stock options and influence pay through proxy votes. CUSTOMERS note compensation is often the largest operating cost and may buy based on how a firm treats employees. MANAGERS view pay as a major expense and a tool to influence behavior, performance and quality. EMPLOYEES view pay as a return for work, an entitlement, or an incentive/reward for performance.",
  "pay-behavior":
    "Pay influences behavior two ways. The INCENTIVE EFFECT: pay affects the intensity, direction and persistence of current employees' motivation. The SORTING EFFECT: how (and how much) an organization pays attracts and retains specific types of employees (e.g., a high-incentive plan attracts risk-takers and high performers).",
  "forms-of-pay":
    "Total returns = Total Compensation + Relational Returns. CASH COMPENSATION includes: base wage (salary for exempt employees with no overtime; hourly wage for nonexempt), merit increases (permanent additions to base for performance), merit bonuses (lump-sum, not permanent), cost-of-living adjustments (COLA), incentives/variable pay (tied to objective measures, must be re-earned each period, explicitly influence future behavior), and long-term incentives (multiyear, e.g., stock options). BENEFITS include income protection (legally required + common like medical/life), work/life balance, and allowances (housing, transport — common internationally). RELATIONAL RETURNS are non-financial: recognition, status, employment security, challenging work and learning.",
  "pay-model":
    "The pay model has three parts: Objectives, Policies and Techniques. The four COMPENSATION OBJECTIVES are: Efficiency (performance, quality, customer/stockholder delight, cost control), Fairness (procedural and distributive equity), Compliance (conforming to federal/state laws), and Ethics (achieving results the right way). The four POLICY CHOICES are: Internal Alignment (comparisons among jobs/skills inside the organization), External Competitiveness (pay comparisons with competitors), Employee Contributions (the pay mix, e.g., flat rate vs. team incentives), and Management (the right people get the right pay for the right objectives).",
  "external-competitiveness":
    "External competitiveness is the pay relationships among organizations — an organization's pay relative to competitors. PAY LEVEL is the average of all rates paid by an employer: (base + bonuses + benefits + value of stock) / number of employees. PAY MIX is the various pay forms that make up total compensation. The two objectives of pay-level and mix decisions are to (1) control costs and increase revenues, and (2) attract and retain employees. Three sets of factors shape it: labor market, product market, and organization factors.",
  "labor-market":
    "How labor markets work: the DEMAND side focuses on employers (how many they hire and what they pay); the SUPPLY side focuses on potential employees (their qualifications and the pay they will accept). Key concepts: Marginal Product of Labor (additional output from one more worker), Marginal Revenue of Labor (additional revenue from one more worker), and Diminishing Marginal Productivity (each new hire produces less than the prior one because other factors are fixed short-term). RULE: an employer hires until the marginal revenue equals the cost of the last hire.",
  "labor-theories":
    "Theories that modify the demand side: Compensating Differentials (Adam Smith — higher wages for jobs with negative characteristics); Efficiency Wage Theory (high wages can LOWER total labor costs by attracting better talent, cutting turnover and raising effort); Signaling Theory (pay level and mix signal the behaviors an employer wants — e.g., low base + high bonus signals a desire for risk-takers); Reservation Wage (the minimum pay below which a job seeker won't accept an offer); and Human Capital (higher earnings flow to those who invest in their own productivity through skills and education).",
  "product-market":
    "The labor market sets the FLOOR (minimum pay needed to attract staff); the product market sets the LID (maximum an employer can afford). Two key product-market factors: Product Demand (if high, costs can be passed to consumers, raising the lid) and Degree of Competition (in highly competitive markets, raising prices loses revenue, lowering the lid). Ability to pay therefore depends on the product market.",
  "pay-policies":
    "Competitive pay policy alternatives: LEAD the market (pay above competitors to attract/retain the best); MATCH / market pricing (pay the same as competitors — the most common); LAG the market (pay below competitors, often combined with other returns like a great culture or future growth); and HYBRID/FLEXIBLE (different policies for different job families). Consequences touch efficiency (high pay can improve performance but raises costs), fairness (employees compare their pay to the market) and compliance.",
  "benefits-growth":
    "Employee benefits are the part of total compensation other than pay for time worked, provided wholly or partly by employer payments (e.g., life insurance, pensions, vacation). Benefits are roughly 31.7% of total compensation; for every dollar of wages they add about 42% on average (up to 54% in large establishments). Reasons for growth: wage and price controls (WWII/Korean War pushed unions and employers toward benefits instead of wage increases); unions (catalysts for pensions, health care, time off); employer impetus (satisfaction, productivity, security); cost-effectiveness (most benefits are NOT taxable, and group plans are cheaper with easier qualification); and government mandates (Social Security, Workers' Comp, Unemployment).",
  "benefits-value":
    "Medical benefits are consistently ranked the most important by employees. A key concern is that employees often undervalue or are unaware of their benefits. The solution is to introduce CHOICE (flexible benefit packages) and improve COMMUNICATION — lack of communication is a root cause of dissatisfaction.",
  "flexible-benefits":
    "Flexible benefit programs let employees choose. Advantages: satisfy the unique needs of a diverse workforce, improve understanding through involvement, new benefits are less costly to introduce, and effective cost containment (a fixed dollar maximum). Disadvantages: employees may make bad choices (lack of coverage), increased administrative burden/expense, ADVERSE SELECTION (those who will use a benefit heavily are the ones who choose it, raising costs), and nondiscrimination requirements (Section 125).",
  "benefits-financing":
    "Three financing methods: Noncontributory (employer pays the total cost), Contributory (cost shared by employer and employee), and Employee-financed (employee pays the total cost). Cost-containment strategies include probationary periods (exclude new hires initially), benefit caps (maximum % or fixed amount), cost sharing (deductibles and co-pays), plus outsourcing, self-insurance, wellness programs and competitive bidding. Claims processing: (1) determine the event occurred, (2) determine eligibility, (3) calculate the payment level with coordination of benefits.",
  "legally-required":
    "Legally required benefits: WORKERS' COMPENSATION (no-fault insurance for injuries/diseases arising during employment; workers can't sue beyond wages and medical care; governed by STATE law). SOCIAL SECURITY & MEDICARE (retirement, disability or death benefits; funded 7.65% worker + 7.65% employer, 15.3% self-employed; categories: old-age/disability, dependents, survivors, lump-sum death). UNEMPLOYMENT INSURANCE (offsets lost income, helps find jobs, varies by state). FMLA (employers with 50+ employees; up to 12 weeks UNPAID leave; guarantees the same/comparable job). COBRA (temporary health-insurance extension up to 36 months after qualifying events; employers with 20+ employees). HIPAA (limits denying coverage for preexisting conditions; bans health-status discrimination).",
  "retirement-plans":
    "DEFINED BENEFIT (DB / pension): the benefit level is promised, the employer bears the risk, cost is fixed, the employee has no active role, and it encourages retention. DEFINED CONTRIBUTION (DC, e.g., 401k): the employer contribution is defined, the EMPLOYEE bears the investment risk, cost varies with ability to pay, the employee must manage investments, and it facilitates mobility. Popular DC plans: 401(k) (defer pretax income, employer often matches), ESOP (company contributes stock to a trust — disadvantage is lack of diversification), and profit sharing (distribution delayed until retirement). Also: cash balance plans (DB that looks like DC) and IRAs (individual tax-favored savings).",
  "insurance-benefits":
    "Life insurance: about 56% of private-sector employees have access, usually group term insurance worth 1–2x annual salary. Short-term disability (STD) pays a percentage of salary for temporary illness/injury. Long-term disability (LTD) kicks in after STD expires.",
  "health-care":
    "Medical/health-care costs are outstripping inflation and worker earnings. Delivery structures: commercial plans, HMO, PPO and POS. Three cost-control strategies: (1) motivate employees to change demand (plan design/administration changes), (2) change the structure of delivery systems, and (3) link incentives to healthy behaviors. Additional benefits include paid time off (PTO, replacing traditional separate time-off plans), family-friendly policies (FSAs for child care), elder care and financial wellness.",
  "intl-factors":
    "International compensation is influenced by economic, institutional and organizational factors and employee characteristics. Five key factors affect international pay: (1) Social Contracts, (2) Culture, (3) Trade Unions, (4) Ownership and Financial Markets, and (5) Managerial Autonomy. Comparing costs across countries can mislead — organizations should evaluate both labor costs AND productivity, and the goal is usually equivalent purchasing power rather than identical salaries.",
  "social-contract":
    "A social contract is the set of expectations and relationships among employees, employers, governments, owners/shareholders and unions; it varies by country and evolves over time. It shapes pay setting: CENTRALIZED pay setting (by governments, national unions or industry-wide agreements) gives wage consistency and less inequality but less employer flexibility; DECENTRALIZED pay setting (each organization decides) gives flexibility and faster market response but more variation. Managerial autonomy is HIGH when government intervention and bargaining are low, and LOW when pay setting is centralized, regulation is extensive and unions are powerful. Union coverage varies widely (France ~99%, Germany ~56%, Japan ~17%, US ~12%, Mexico ~10%). Research suggests national culture is a useful context but less of a hard constraint than once thought (HPWS work across many cultures).",
  "japan-germany":
    "Traditional JAPANESE system — three pillars: lifetime employment, seniority-based pay and enterprise unions. It is PERSON-based (not job-based), emphasizes seniority/skills, internal equity and employment security; components are base pay (by career category, years of service, skills, performance), bonuses (twice a year, 1–5 months of pay, expected and culturally rooted, not always performance-linked), and benefits/allowances. Traditional GERMAN system — based on social partnership among employers, unions and government; heavily regulated (90+ laws), with industry-specific TARIFF agreements defining pay grades and progression; base pay depends on job descriptions, job evaluation and employee age; bonuses were traditionally uncommon but are rising; generous benefits and more vacation than US workers. The US has greater managerial flexibility, stronger performance orientation and a shorter-term focus.",
  "global-mindset":
    "Strategic market mind-sets for global pay: LOCALIZER ('think global, act local') uses a different compensation system in each country; EXPORTER ('headquarters knows best') exports home-country practices abroad; GLOBALIZER ('think globally and locally') builds a common global framework while allowing local adaptation.",
  "expatriate-pay":
    "Expatriates temporarily work outside their home country. Types: Parent-Country Nationals (PCNs, from the firm's home country), Third-Country Nationals (TCNs, from neither home nor host) and Local-Country Nationals (LCNs, from the host country). Expat pay elements: salary (via job evaluation/leveling), taxes (often tax equalization), housing assistance, and allowances/premiums (hardship, cost-of-living, relocation). The BALANCE SHEET APPROACH is the most widely used method — it keeps equivalent purchasing power and standard of living between home and host (components: base salary, taxes, housing, goods and services, incentives). Alternatives: negotiation, localization, modified balance sheet (regional comparisons), lump-sum/cafeteria, and greater use of local employees. Challenges: uncertain career paths and lower-level jobs on repatriation, reduced disposable income, little recognition of international experience, and high turnover among returning expatriates.",
};

/* ───────────────────────────── Questions ───────────────────────────── */

const Q = (
  id: string,
  difficulty: Question["difficulty"],
  type: Question["type"],
  chapter: Chapter,
  topic: string,
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question => ({ id, difficulty, type, chapter, topic, prompt, options, correctIndex, explanation });

const questions: Question[] = [
  // ════════════ Chapter 1 — The Pay Model ════════════
  Q("pm-e1", "easy", "definition", 1, "pay-behavior",
    "The 'incentive effect' of pay refers to how pay affects:",
    ["The intensity, direction and persistence of current employees' motivation", "The number of job applicants only", "The company's tax rate", "The product's market price"],
    0, "The incentive effect is pay's influence on the motivation (intensity, direction, persistence) of current employees."),
  Q("pm-e2", "easy", "definition", 1, "pay-behavior",
    "The 'sorting effect' of pay refers to how pay:",
    ["Attracts and retains specific types of employees", "Sets the company's share price", "Calculates overtime", "Determines tax brackets"],
    0, "The sorting effect: how and how much a firm pays attracts and retains particular types of employees."),
  Q("pm-e3", "easy", "definition", 1, "forms-of-pay",
    "A salaried 'exempt' employee is one who:",
    ["Is not eligible for overtime pay", "Is always paid hourly", "Receives only bonuses", "Pays no income tax"],
    0, "Exempt employees are salaried and not eligible for overtime; nonexempt employees are paid hourly."),
  Q("pm-e4", "easy", "true-false", 1, "comp-matters",
    "Compensation is both a major cost to manage and a tool to influence employee behavior.",
    ["True", "False"], 0,
    "Pay affects efficiency/quality (a cost) and influences behavior, performance and quality (a strategic tool)."),
  Q("pm-e5", "easy", "definition", 1, "pay-model",
    "Which is one of the four compensation OBJECTIVES in the pay model?",
    ["Efficiency", "Internal alignment", "External competitiveness", "Employee contributions"],
    0, "The four objectives are Efficiency, Fairness, Compliance and Ethics. The others listed are POLICY choices."),
  Q("pm-m1", "medium", "comparison", 1, "forms-of-pay",
    "What is the key difference between a merit increase and a merit bonus?",
    ["A merit increase permanently raises base pay; a merit bonus is a one-time lump sum", "They are identical", "A merit bonus is permanent; an increase is temporary", "A merit increase is non-taxable"],
    0, "Merit increases are permanent additions to base pay; merit bonuses are lump-sum payments that are not permanent."),
  Q("pm-m2", "medium", "multiple-choice", 1, "forms-of-pay",
    "Variable pay (incentives) differs from base pay because incentives:",
    ["Must be re-earned each period and explicitly influence future behavior", "Are guaranteed every year", "Never depend on performance", "Are part of relational returns"],
    0, "Incentives are tied to objective performance measures, must be re-earned each period, and explicitly aim to shape future behavior."),
  Q("pm-m3", "medium", "multiple-choice", 1, "pay-stakeholders",
    "From SOCIETY's perspective, compensation is often viewed as:",
    ["A measure of justice/equity, e.g., male/female earning differentials", "Only an operating cost", "A proxy voting tool", "A relational return"],
    0, "Society views pay as a measure of justice/equity (such as gender earning differentials)."),
  Q("pm-m4", "medium", "multiple-choice", 1, "pay-model",
    "'Comparisons among jobs and skills INSIDE the organization' describes which policy choice?",
    ["Internal alignment", "External competitiveness", "Employee contributions", "Management"],
    0, "Internal alignment concerns pay comparisons among jobs/skills inside the organization."),
  Q("pm-h1", "hard", "scenario", 1, "pay-model",
    "A firm benchmarks its pay against competitors to improve recruitment and retention. Which policy choice is this?",
    ["External competitiveness", "Internal alignment", "Ethics", "Employee contributions"],
    0, "External competitiveness is pay comparisons with competitors, affecting recruitment and retention."),
  Q("pm-h2", "hard", "scenario", 1, "forms-of-pay",
    "An employer gives staff recognition, employment security and challenging work. In the forms-of-pay framework these are:",
    ["Relational returns (non-financial)", "Cash compensation", "Legally required benefits", "Long-term incentives"],
    0, "Recognition, status, security, challenging work and learning are relational (non-financial) returns."),
  Q("pm-h3", "hard", "comparison", 1, "pay-behavior",
    "A startup offers low base salary but large stock options, attracting ambitious risk-takers. This best illustrates the:",
    ["Sorting effect", "Incentive effect", "Compliance objective", "Cost-of-living adjustment"],
    0, "Attracting a particular TYPE of employee through the pay package is the sorting effect."),

  // ════════════ Chapter 7 — Defining Competitiveness ════════════
  Q("ec-e1", "easy", "definition", 7, "external-competitiveness",
    "External competitiveness refers to:",
    ["An organization's pay relative to its competitors", "Pay differences among jobs inside the firm", "The firm's tax strategy", "The product's selling price"],
    0, "External competitiveness is the pay relationship among organizations — pay relative to competitors."),
  Q("ec-e2", "easy", "definition", 7, "external-competitiveness",
    "'Pay level' is best defined as:",
    ["The average of all rates paid by an employer", "The highest salary in the firm", "The CEO's bonus", "The minimum wage"],
    0, "Pay level = (base + bonuses + benefits + stock value) / number of employees — the average rate paid."),
  Q("ec-e3", "easy", "definition", 7, "pay-policies",
    "Paying the SAME as competitors (the most common policy) is called:",
    ["Match (market pricing)", "Lead", "Lag", "Hybrid"],
    0, "Matching / market pricing means paying the same as competitors and is the most common policy."),
  Q("ec-e4", "easy", "true-false", 7, "labor-market",
    "On the demand side of the labor market, the focus is on employers — how many they hire and what they pay.",
    ["True", "False"], 0,
    "Demand side = employers (hiring and pay); supply side = potential employees (qualifications and pay accepted)."),
  Q("ec-m1", "medium", "comparison", 7, "product-market",
    "In setting pay, the labor market and product market play which roles?",
    ["Labor market sets the floor (minimum); product market sets the lid (maximum)", "Both set the minimum", "Labor market sets the lid; product market the floor", "Neither affects pay"],
    0, "The labor market sets the floor (minimum to attract staff); the product market sets the lid (what the employer can afford)."),
  Q("ec-m2", "medium", "multiple-choice", 7, "labor-theories",
    "Efficiency Wage Theory argues that paying high wages can:",
    ["Lower total labor costs by attracting better talent, cutting turnover and raising effort", "Always increase total labor costs", "Reduce product demand", "Eliminate the need for benefits"],
    0, "Efficiency wage theory: high wages may lower total labor costs via better talent, lower turnover and more effort."),
  Q("ec-m3", "medium", "multiple-choice", 7, "labor-theories",
    "The minimum pay below which a job seeker will not accept an offer is the:",
    ["Reservation wage", "Compensating differential", "Marginal revenue", "Efficiency wage"],
    0, "The reservation wage is the minimum acceptable pay level for a job seeker."),
  Q("ec-m4", "medium", "multiple-choice", 7, "labor-market",
    "Diminishing marginal productivity means that, in the short term, each additional hire:",
    ["Produces less than the previous one because other factors are fixed", "Produces more than the previous one", "Has no effect on output", "Lowers the firm's taxes"],
    0, "Because other production factors are fixed short-term, each new hire adds less output than the prior one."),
  Q("ec-h1", "hard", "scenario", 7, "labor-theories",
    "A mining firm pays extra for dangerous, remote work. Per Adam Smith, this premium is a:",
    ["Compensating differential", "Signaling effect", "Reservation wage", "Human capital return"],
    0, "Compensating differentials are higher wages paid for jobs with negative characteristics."),
  Q("ec-h2", "hard", "scenario", 7, "pay-policies",
    "A prestigious nonprofit pays below market but offers a great mission and culture. Its pay-level policy is to:",
    ["Lag the market (combined with other returns)", "Lead the market", "Match the market", "Use a balance sheet approach"],
    0, "Lagging pays below competitors, often offset by other returns such as culture, mission or growth."),
  Q("ec-h3", "hard", "scenario", 7, "product-market",
    "In a highly competitive product market, why is an employer's ability to raise pay limited?",
    ["Raising prices to cover higher pay would lose revenue to competitors", "Labor supply is unlimited", "Benefits are untaxed", "Unions set all wages"],
    0, "High product-market competition lowers the 'lid': prices can't easily rise, so ability to pay is constrained."),
  Q("ec-h4", "hard", "comparison", 7, "labor-theories",
    "A firm advertises 'low base, high bonus' pay. According to Signaling Theory this communicates that the employer wants:",
    ["Risk-takers / strong performers", "Risk-averse, tenure-focused staff", "Only part-time workers", "Lower-skilled labor"],
    0, "Pay mix signals desired behavior; low base + high bonus signals a preference for risk-takers and high performers."),

  // ════════════ Chapter 12 — Benefit Determination ════════════
  Q("bd-e1", "easy", "definition", 12, "benefits-growth",
    "Employee benefits are best defined as:",
    ["Part of total compensation other than pay for time worked, provided by employer payments", "Only the base salary", "Cash bonuses for performance", "Overtime pay"],
    0, "Benefits are the part of total compensation other than pay for time worked (e.g., insurance, pensions, vacation)."),
  Q("bd-e2", "easy", "true-false", 12, "benefits-growth",
    "A major reason benefits grew is that most benefits are not taxable to the employee.",
    ["True", "False"], 0,
    "Cost-effectiveness: most benefits are not taxable, and group plans are cheaper with easier qualification."),
  Q("bd-e3", "easy", "definition", 12, "benefits-value",
    "Which benefit is consistently ranked MOST important by employees?",
    ["Medical benefits", "Company car", "Gym membership", "Free parking"],
    0, "Medical benefits are consistently ranked the most important by employees."),
  Q("bd-e4", "easy", "definition", 12, "benefits-financing",
    "Under a 'noncontributory' financing method:",
    ["The employer pays the total cost", "The employee pays the total cost", "Cost is split equally", "The government pays"],
    0, "Noncontributory = employer pays the total cost; contributory = shared; employee-financed = employee pays all."),
  Q("bd-m1", "medium", "multiple-choice", 12, "flexible-benefits",
    "Which is an ADVANTAGE of flexible benefit programs?",
    ["They satisfy the unique needs of a diverse workforce", "They guarantee employees never make bad choices", "They eliminate administrative work", "They remove adverse selection"],
    0, "Advantages include meeting diverse needs, involvement/understanding, cheaper new benefits, and cost containment."),
  Q("bd-m2", "medium", "multiple-choice", 12, "flexible-benefits",
    "In flexible benefits, 'adverse selection' means:",
    ["Those who will use a benefit heavily are the ones who choose it, raising costs", "Employees pick the cheapest plan", "The employer selects benefits for everyone", "Benefits are chosen randomly"],
    0, "Adverse selection: heavy utilizers self-select into a benefit, increasing its cost — a disadvantage of choice."),
  Q("bd-m3", "medium", "multiple-choice", 12, "benefits-value",
    "Employees often undervalue benefits. The two recommended fixes are:",
    ["Introduce choice (flexibility) and improve communication", "Cut benefits and raise base pay", "Remove medical coverage", "Eliminate flexible plans"],
    0, "The solution to undervaluation is offering choice (flexible packages) and improving communication."),
  Q("bd-m4", "medium", "multiple-choice", 12, "benefits-financing",
    "Which is a cost-containment strategy in benefits administration?",
    ["Deductibles and co-pays (cost sharing)", "Removing all probationary periods", "Unlimited benefit caps", "Paying every claim without checks"],
    0, "Cost containment includes probationary periods, benefit caps, cost sharing (deductibles/co-pays), wellness, etc."),
  Q("bd-h1", "hard", "scenario", 12, "flexible-benefits",
    "After a firm lets employees pick their own benefits, costs rise because the heaviest users chose the richest options. This is:",
    ["Adverse selection", "A compensating differential", "Coordination of benefits", "Tax equalization"],
    0, "When heavy utilizers self-select into generous options, costs climb — the adverse-selection disadvantage."),
  Q("bd-h2", "hard", "scenario", 12, "benefits-financing",
    "What is the correct order of the claims-processing steps?",
    ["Determine the event occurred → determine eligibility → calculate payment", "Calculate payment → determine eligibility → determine the event", "Determine eligibility → calculate payment → determine the event", "Pay first, verify later"],
    0, "Claims processing: (1) the event occurred, (2) eligibility, (3) payment level with coordination of benefits."),
  Q("bd-h3", "hard", "comparison", 12, "benefits-growth",
    "Why did wage and price controls during WWII/Korea boost benefit growth?",
    ["Unions and employers sought benefits instead of restricted wage increases", "They raised taxes on benefits", "They banned pensions", "They mandated lower benefits"],
    0, "With wages capped, parties turned to non-wage benefits — a historical driver of benefit growth."),

  // ════════════ Chapter 13 — Benefit Options ════════════
  Q("bo-e1", "easy", "definition", 13, "legally-required",
    "Workers' compensation is governed primarily by:",
    ["State laws", "Federal law only", "Company policy", "Union contracts only"],
    0, "Workers' compensation is no-fault insurance governed by state laws, not federal."),
  Q("bo-e2", "easy", "definition", 13, "legally-required",
    "FMLA provides eligible employees up to:",
    ["12 weeks of UNPAID leave", "12 weeks of paid leave", "6 months of paid leave", "4 weeks of unpaid leave"],
    0, "FMLA (employers with 50+ employees) gives up to 12 weeks of unpaid leave with a job guarantee."),
  Q("bo-e3", "easy", "definition", 13, "legally-required",
    "COBRA allows a temporary extension of which benefit after a qualifying event like a layoff?",
    ["Health insurance", "Stock options", "Paid vacation", "Pension contributions"],
    0, "COBRA extends health insurance (up to 36 months) after qualifying events; applies to employers with 20+ employees."),
  Q("bo-e4", "easy", "true-false", 13, "retirement-plans",
    "In a defined contribution plan (e.g., 401k), the employee bears the investment risk.",
    ["True", "False"], 0,
    "In DC plans the employee bears the risk and manages investments; in DB plans the employer bears the risk."),
  Q("bo-e5", "easy", "definition", 13, "insurance-benefits",
    "Long-term disability (LTD) insurance typically begins:",
    ["After short-term disability (STD) expires", "On the first day of illness", "Only after retirement", "Before STD"],
    0, "LTD kicks in after STD coverage expires."),
  Q("bo-m1", "medium", "comparison", 13, "retirement-plans",
    "Which statement correctly contrasts DB and DC plans?",
    ["DB encourages retention and the employer bears risk; DC facilitates mobility and the employee bears risk", "Both put risk on the employer", "DC promises a fixed benefit level", "DB requires employees to manage investments"],
    0, "DB: promised benefit, employer risk, retention. DC: defined contribution, employee risk/management, mobility."),
  Q("bo-m2", "medium", "multiple-choice", 13, "retirement-plans",
    "A noted disadvantage of an ESOP is:",
    ["Lack of diversification (concentrated in company stock)", "It is illegal", "It pays no benefit", "It is fully taxed immediately"],
    0, "An ESOP contributes company stock to a trust; its disadvantage is poor diversification."),
  Q("bo-m3", "medium", "multiple-choice", 13, "legally-required",
    "Social Security is funded by contributions of:",
    ["7.65% from workers and 7.65% from employers (15.3% self-employed)", "100% from the employer", "100% from the government", "A flat $1,000 per worker"],
    0, "Funding: 7.65% worker + 7.65% employer; self-employed pay 15.3%."),
  Q("bo-m4", "medium", "multiple-choice", 13, "health-care",
    "Which is a recognized health-care COST-CONTROL strategy?",
    ["Link incentives to healthy behaviors", "Remove all delivery structures", "Pay every claim without review", "Ban PPOs and HMOs"],
    0, "Strategies: change demand via plan design, change the delivery structure, and link incentives to healthy behavior."),
  Q("bo-h1", "hard", "scenario", 13, "retirement-plans",
    "An employer wants a plan whose cost varies with ability to pay and that helps employees who change jobs. Best fit:",
    ["A defined contribution (DC) plan", "A defined benefit (DB) pension", "Workers' compensation", "COBRA"],
    0, "DC plans have costs that vary with ability to pay and facilitate mobility — unlike fixed-cost DB pensions."),
  Q("bo-h2", "hard", "scenario", 13, "legally-required",
    "A 60-employee firm must let a worker take unpaid leave for a new baby and return to a comparable job. Which law applies?",
    ["FMLA", "COBRA", "HIPAA", "Workers' compensation"],
    0, "FMLA (50+ employees) provides up to 12 weeks unpaid leave with a same/comparable-job guarantee."),
  Q("bo-h3", "hard", "scenario", 13, "legally-required",
    "An employee worries a new insurer will deny coverage for a preexisting condition. Which law offers protection?",
    ["HIPAA", "FMLA", "COBRA", "Unemployment insurance"],
    0, "HIPAA lessens the ability to deny coverage for preexisting conditions and bars health-status discrimination."),
  Q("bo-h4", "hard", "comparison", 13, "retirement-plans",
    "A cash balance plan is best described as:",
    ["A defined benefit plan that looks like a defined contribution plan", "A pure 401(k)", "An IRA", "A health savings account"],
    0, "Cash balance plans are DB plans designed to look like DC plans (accounts grow with contributions + fixed interest)."),

  // ════════════ Chapter 16 — International Pay ════════════
  Q("ip-e1", "easy", "definition", 16, "intl-factors",
    "Which is one of the five key factors affecting international pay?",
    ["Social contracts", "The local weather", "The CEO's age", "Office floor plans"],
    0, "The five factors: social contracts, culture, trade unions, ownership/financial markets, and managerial autonomy."),
  Q("ip-e2", "easy", "definition", 16, "expatriate-pay",
    "A 'Parent-Country National' (PCN) is:",
    ["A citizen of the organization's home country", "A citizen of the host country", "A citizen of a third country", "A contractor with no citizenship"],
    0, "PCN = home-country citizen; LCN = host-country citizen; TCN = a country other than home or host."),
  Q("ip-e3", "easy", "definition", 16, "expatriate-pay",
    "The most widely used method of expatriate compensation is the:",
    ["Balance sheet approach", "Lump-sum lottery", "Profit-sharing plan", "Cash balance plan"],
    0, "The balance sheet approach keeps equivalent purchasing power/standard of living between home and host."),
  Q("ip-e4", "easy", "true-false", 16, "japan-germany",
    "The three traditional pillars of the Japanese system are lifetime employment, seniority-based pay and enterprise unions.",
    ["True", "False"], 0,
    "Those are exactly the three traditional pillars of the Japanese compensation system."),
  Q("ip-m1", "medium", "comparison", 16, "social-contract",
    "Compared with decentralized pay setting, CENTRALIZED pay setting tends to produce:",
    ["More wage consistency and less inequality, but less employer flexibility", "More pay variation", "Faster response to the market", "No government involvement"],
    0, "Centralized setting (governments/national unions/industry agreements) gives consistency but less flexibility."),
  Q("ip-m2", "medium", "comparison", 16, "japan-germany",
    "A core contrast between the Japanese and German systems is that:",
    ["Japan is person-based (seniority/skills); Germany is job-based (job evaluation, tariff agreements)", "Both are purely performance-based", "Germany is person-based and Japan is job-based", "Neither uses unions"],
    0, "Japanese pay is person-based and seniority-focused; German pay is job-based and regulated via tariff agreements."),
  Q("ip-m3", "medium", "multiple-choice", 16, "global-mindset",
    "A 'Globalizer' strategic mind-set means the firm:",
    ["Builds a common global framework while allowing local adaptation", "Uses a totally different system in each country", "Exports only home-country practices", "Avoids all international pay"],
    0, "Globalizer = 'think globally and locally': a common framework with room for local adaptation."),
  Q("ip-m4", "medium", "multiple-choice", 16, "intl-factors",
    "Why can simple international wage comparisons be misleading?",
    ["They ignore healthcare, benefits, living costs and productivity differences", "Wages are identical everywhere", "Taxes are the same in all countries", "Productivity never varies"],
    0, "Comparisons must weigh benefits, living costs and productivity; the goal is equivalent purchasing power."),
  Q("ip-m5", "medium", "multiple-choice", 16, "japan-germany",
    "Japanese bonuses are typically:",
    ["Paid twice a year (1–5 months of pay) and expected, not always performance-linked", "Paid only for top performers", "Banned by law", "A one-time signing bonus"],
    0, "Japanese bonuses are paid twice yearly, equal 1–5 months of pay, are culturally expected and not strictly performance-based."),
  Q("ip-h1", "hard", "scenario", 16, "social-contract",
    "In a country with centralized pay, extensive regulation and powerful unions, managerial autonomy over pay is:",
    ["Low", "High", "Unlimited", "Unaffected"],
    0, "Managerial autonomy is low when pay setting is centralized, regulation is extensive and unions are powerful."),
  Q("ip-h2", "hard", "scenario", 16, "expatriate-pay",
    "A company sends a US manager to Germany and uses tax equalization, housing and a hardship premium to keep her standard of living equal to home. This is the:",
    ["Balance sheet approach", "Localization approach", "Lump-sum/cafeteria approach", "Negotiation approach"],
    0, "Keeping equivalent purchasing power/standard of living via base, taxes, housing, goods and incentives is the balance sheet approach."),
  Q("ip-h3", "hard", "scenario", 16, "expatriate-pay",
    "A common challenge expatriates face upon returning home (repatriation) is:",
    ["Lower-level jobs and little recognition of international experience, leading to high turnover", "Automatic promotion and a raise", "Guaranteed executive roles", "Permanent tax exemption"],
    0, "Repatriation challenges: uncertain/lower-level roles, reduced disposable income, little recognition, high turnover."),
  Q("ip-h4", "hard", "comparison", 16, "japan-germany",
    "The German compensation system is built on 'social partnership' among:",
    ["Employers, labor unions and government", "Only shareholders and managers", "Banks and customers", "Expatriates and locals"],
    0, "German pay rests on social partnership among employers, unions and government, with heavy regulation and tariff agreements."),
];

/* ───────────────────────────── Subject ───────────────────────────── */

export const compensationManagement: Subject = {
  id: "compensation-management",
  name: { en: "Compensation Management", ar: "إدارة التعويضات" },
  tagline: {
    en: "Milkovich · The Pay Model, Competitiveness, Benefits & International Pay",
    ar: "ميلكوفيتش · نموذج الأجر والتنافسية والمزايا والأجور الدولية · الفصول ١ و٧ و١٢ و١٣ و١٦",
  },
  icon: "Wallet",
  accent: "#f59e0b",
  glow: "rgba(245, 158, 11, 0.45)",
  chapters: [1, 7, 12, 13, 16],
  chapterTitles: {
    1: { en: "The Pay Model", ar: "نموذج الأجر" },
    7: { en: "Defining Competitiveness", ar: "تحديد التنافسية" },
    12: { en: "The Benefit Determination Process", ar: "عملية تحديد المزايا" },
    13: { en: "Benefit Options", ar: "خيارات المزايا" },
    16: { en: "International Pay Systems", ar: "أنظمة الأجور الدولية" },
  },
  topics,
  questions,
  essays: COMPENSATION_MANAGEMENT_ESSAYS,
  knowledge,
  available: true,
};
