import type { Bilingual, Chapter, Question } from "../types";
import type { Subject, SubjectTopic } from "./services-marketing";

/* ───────────────────────────── Topics ───────────────────────────── */

const T = (id: string, en: string, ar: string, chapter: Chapter): SubjectTopic => ({
  id,
  label: { en, ar },
  chapter,
});

const topics: Record<string, SubjectTopic> = {
  // Ch 8 — FDI
  "fdi-basics": T("fdi-basics", "FDI Basics", "أساسيات الاستثمار الأجنبي المباشر", 8),
  "fdi-forms": T("fdi-forms", "Forms of FDI", "أشكال الاستثمار الأجنبي", 8),
  "fdi-theories": T("fdi-theories", "Theories of FDI", "نظريات الاستثمار الأجنبي", 8),
  "fdi-management": T("fdi-management", "FDI Management Issues", "القضايا الإدارية في الاستثمار", 8),
  "fdi-government": T("fdi-government", "Government Intervention in FDI", "تدخل الحكومات في الاستثمار", 8),
  "balance-of-payments": T("balance-of-payments", "Balance of Payments", "ميزان المدفوعات", 8),
  // Ch 9 — Regional Integration
  "regional-integration": T("regional-integration", "Regional Integration", "التكامل الإقليمي", 9),
  "integration-levels": T("integration-levels", "Levels of Integration", "مستويات التكامل", 9),
  "integration-effects": T("integration-effects", "Benefits & Drawbacks", "الفوائد والعيوب", 9),
  "trading-blocs": T("trading-blocs", "Trading Blocs", "الكتل التجارية الإقليمية", 9),
  // Ch 11 — Monetary System
  "currency-values": T("currency-values", "Currency Values", "قيم العملة", 11),
  "exchange-determinants": T("exchange-determinants", "Exchange Rate Determinants", "محددات أسعار الصرف", 11),
  ppp: T("ppp", "Purchasing Power Parity", "تعادل القوة الشرائية", 11),
  "fixed-rates": T("fixed-rates", "Fixed Exchange Systems", "أنظمة الصرف الثابتة", 11),
  "floating-rates": T("floating-rates", "Floating Exchange Systems", "أنظمة الصرف العائمة", 11),
  // Ch 12 — Strategy & Organization
  "company-analysis": T("company-analysis", "Company Analysis", "تحليل الشركة", 12),
  "intl-strategies": T("intl-strategies", "International Strategies", "الاستراتيجيات الدولية", 12),
  "corporate-strategies": T("corporate-strategies", "Corporate-Level Strategies", "استراتيجيات مستوى الشركة", 12),
  "business-strategies": T("business-strategies", "Business-Level Strategies", "استراتيجيات مستوى الأعمال", 12),
  "org-structure": T("org-structure", "Organizational Structure", "الهيكل التنظيمي", 12),
  "org-types": T("org-types", "Structure Types & Teams", "أنواع الهياكل والفِرَق", 12),
  // Ch 13 — Analyzing Opportunities
  "market-research": T("market-research", "Market Research", "أبحاث السوق", 13),
  "market-screening": T("market-screening", "Market & Site Screening", "فحص الأسواق والمواقع", 13),
  "market-potential": T("market-potential", "Measuring Market Potential", "قياس إمكانات السوق", 13),
  "research-methods": T("research-methods", "Research Methods", "أساليب البحث", 13),
  // Ch 14 — Entry Modes
  "entry-modes": T("entry-modes", "Entry Modes Overview", "نظرة عامة على أنماط الدخول", 14),
  exporting: T("exporting", "Exporting", "التصدير", 14),
  countertrade: T("countertrade", "Countertrade", "التجارة المقابلة", 14),
  "export-financing": T("export-financing", "Export/Import Financing", "تمويل التصدير والاستيراد", 14),
  "contractual-entry": T("contractual-entry", "Contractual Entry", "الدخول التعاقدي", 14),
  "investment-entry": T("investment-entry", "Investment Entry", "الدخول الاستثماري", 14),
};

/* ─────────────────────────── Knowledge base ─────────────────────────── */

const knowledge: Record<string, string> = {
  "fdi-basics":
    "Foreign Direct Investment (FDI) is the purchase of physical assets or a significant amount of ownership (stock) of a company in another country to gain a measure of management control. It contrasts with Portfolio Investment, which does not involve obtaining a degree of control in a company. Global FDI flows are measured by totaling inflows to all countries over a year; flows grew strongly since the 1990s. Historically developed nations were the biggest recipients, but in 2014 developing nations attracted more (about 55% of the global total) for the first time, and China was the leading recipient in 2020. Developed nations remain the main source of most investment.",
  "fdi-forms":
    "FDI takes two main forms. A Greenfield Investment is buying land in another country and building new facilities (a wholly owned subsidiary) from scratch. A Merger or Acquisition gains a foothold in a new geographic market, increases a firm's global competitiveness, fills gaps in product lines, and can reduce R&D, production and distribution costs.",
  "fdi-theories":
    "Four theories explain FDI. (1) International Product Life Cycle: a firm begins by exporting, then invests directly as the product moves through its life cycle (new, maturing, standardized) — but it doesn't fully explain why firms invest rather than license/export. (2) Market Imperfections (internalization): a firm invests when market imperfections (trade barriers, specialized knowledge) make transactions inefficient, so it internalizes the transaction to remove the imperfection. (3) Eclectic Theory: firms invest when a location advantage combines with ownership and internalization advantages (OLI). (4) Market Power: a firm invests to establish a dominant position, often via vertical integration — backward (supply of inputs) or forward (absorbing outputs).",
  "fdi-management":
    "Key managerial issues in FDI: CONTROL — firms want control over local operations; governments may require partnerships/joint ownership, and even full ownership doesn't guarantee control (governments may force hiring local managers or exporting all output). PURCHASE-OR-BUILD — acquisition gives ready facilities/equipment/staff, while building (greenfield) is preferred when no suitable facilities exist or upgrading is too costly (common in developing nations). PRODUCTION COSTS — rationalized production produces each component where it is cheapest; high R&D costs drive cross-border alliances/acquisitions. CUSTOMER KNOWLEDGE — a local presence builds buyer knowledge; firms follow customers (e.g., Tesla and its suppliers) and follow competitors ('follow the leader') to avoid being shut out of profitable markets.",
  "fdi-government":
    "Governments intervene in FDI. A HOST country intervenes to control its balance of payments, gain technology/skills and increase employment; its concerns include draining foreign-exchange reserves when profits are repatriated and harm to uncompetitive local firms. Host policy tools: promotion (financial incentives such as tax breaks and low-interest loans, plus infrastructure) and restriction (ownership restrictions in cultural/national-security industries, performance requirements). A HOME country intervenes to affect its balance of payments, protect domestic jobs, and improve long-term competitiveness by encouraging 'national champions'. Home tools: promotion (insurance, loans, tax breaks, political pressure) and restriction (differential tax rates or outright sanctions).",
  "balance-of-payments":
    "The Balance of Payments is a national accounting system that records all receipts from and payments to foreign entities. The current account records exports and imports of goods and services and income. The capital account records transactions involving the purchase and sale of assets.",
  "regional-integration":
    "Regional Economic Integration (regionalism) is the process by which countries in a geographic region cooperate to reduce or eliminate barriers to the international flow of products, people, or capital. A Regional Trading Bloc is a group of nations in a geographic region undergoing economic integration.",
  "integration-levels":
    "There are five levels of regional integration, increasing in depth: (1) Free Trade Area — members remove all barriers to trade among themselves but each sets its own barriers against nonmembers; (2) Customs Union — remove internal barriers and set a common trade policy against nonmembers; (3) Common Market — remove barriers to trade and to the movement of labor and capital, with a common external trade policy; (4) Economic Union — all of the above plus coordinated economic policies; (5) Political Union — economic and political integration where countries coordinate aspects of their economic and political systems.",
  "integration-effects":
    "Benefits of regional integration: Trade Creation (increase in trade between members), Greater Consensus (easier agreement among fewer nations), Political Cooperation (reduces the potential for military conflict), Employment Opportunities, and Corporate Savings (lower barriers cut the cost of doing business). Drawbacks: Trade Diversion (trade shifts away from more efficient nonmembers toward less efficient members), Shifts in Employment (jobs move to lower-wage or more efficient nations), and Loss of National Sovereignty (giving up control over some national policies to a central regional body).",
  "trading-blocs":
    "Major blocs: in Europe, the European Union (EU) is the most advanced example of integration. In the Americas: NAFTA/USMCA (USA, Canada, Mexico), CAFTA-DR, the Andean Community (CAN), and MERCOSUR (Southern Common Market). In Asia, the Middle East and Africa: ASEAN (Association of Southeast Asian Nations), the GCC (Gulf Cooperation Council, among Arabian Gulf nations), and the African Union (AU).",
  "currency-values":
    "Currency values influence global demand for products. A weak (depreciating) currency lowers export prices and raises import prices, helping a company gain market share; a strong currency improves profits when selling in strong-currency markets while sourcing from weak-currency countries. Values also affect the translated profit from international subsidiaries into the home currency. Devaluation is intentionally lowering a currency's value to boost exports; revaluation is intentionally raising it to reduce import prices and increase buying power. Managers prefer stable, predictable rates for planning. In the efficient market view, prices reflect all public information and forward rates are accurate forecasts; in the inefficient market view they don't, so private information can improve forecasts. Forecasting uses fundamental analysis (economic indicators) and technical analysis (charts of past price trends).",
  "exchange-determinants":
    "The Law of One Price says an identical product must have an identical price in all countries when expressed in a common currency; a violation creates an Arbitrage opportunity (quick purchase and resale for profit). Governments influence money supply and inflation through monetary policy (directly affecting interest rates or money supply, e.g., buying/selling government securities) and fiscal policy (indirectly via taxes and government spending). Low unemployment can push wages, costs and inflation up; low interest rates encourage borrowing/spending (inflationary) while high rates cool the economy.",
  ppp:
    "Purchasing Power Parity (PPP) holds that the exchange rate between two currencies equals the ratio of their price levels, applied to a 'basket' of goods rather than a single product. The Economist's Big Mac Index is a simplified PPP measure. Exchange rates adjust to different inflation rates: high inflation erodes purchasing power and depreciates a currency. PPP predicts long-term rates (10+ years) better than short-term, because of transportation costs, trade barriers, and business confidence/human psychology.",
  "fixed-rates":
    "Fixed systems: the Gold Standard linked paper currency values to specific values of gold (a Par Value). Advantages: reduced exchange-rate risk, strict monetary discipline, and help correcting trade imbalances. It collapsed (dead by 1939) due to aggressive printing of money (inflation) and competitive devaluations. The Bretton Woods Agreement (1944) built a system on the US dollar fixed at $35/oz of gold, creating the World Bank (financing post-WWII reconstruction and developing countries) and the IMF (which regulated the system and created Special Drawing Rights, SDR). It collapsed due to US trade/budget deficits and a weak dollar (Smithsonian Agreement, 1971).",
  "floating-rates":
    "Floating systems: the Jamaica Agreement (1976) formalized floating exchange rates. A managed float lets currencies float with government intervention to stabilize at target rates; a free float has no government intervention. Recent arrangements include a pegged exchange rate (tying a currency to a more stable one such as the USD) and a currency board (a commitment to exchange domestic currency for a specific foreign currency at a fixed rate). The IMF has intervened in crises in Mexico, Southeast Asia, Russia and Argentina. Reform debate focuses on transparency/accountability, international standards, private-sector participation in crisis resolution, and addressing 'moral hazard' (bailouts reducing caution in private lending).",
  "company-analysis":
    "Planning is identifying objectives and deciding how to achieve them; strategy is the planned actions to meet objectives. A mission statement says why a company exists and what it plans to accomplish, considering stakeholders. Objectives get more concrete down the hierarchy: highest level (general terms), business-unit level (specific/numerical), department level (precise/numerical). A core competency is a special ability difficult for competitors to equal, combining multiple coordinated skills. Value Chain Analysis divides activities into primary (logistics, production, marketing, sales, service) and support (infrastructure, HR, technology development, procurement) to find where value is created. PESTLE analysis examines Political, Economic, Social, Technological, Legal and Environmental factors.",
  "intl-strategies":
    "Two international strategies. A Multinational (multidomestic) strategy adapts products and marketing to local preferences: it monitors buyer preferences closely and is seen as high value, but cannot exploit scale economies and has a higher cost structure. A Global strategy offers the same products and marketing in all markets: it saves cost through standardization (scale and location economies) and knowledge sharing, but may overlook important local differences.",
  "corporate-strategies":
    "Corporate-level strategies: Growth (increasing scale/size or scope/kinds of activities, via organic growth or M&A/joint ventures); Retrenchment (reducing scale/scope — closing factories, layoffs — due to poor conditions); Stability (guarding against change, maintaining the current position); and Combination (mixing these across different business units).",
  "business-strategies":
    "Business-level strategies: Low-Cost Leadership (exploiting economies of scale for the lowest cost structure); Differentiation (designing unique products to enjoy higher prices and loyalty); and Focus (serving a narrowly defined segment through either low cost or differentiation).",
  "org-structure":
    "Organizational structure is how a company divides and coordinates activities. Centralization keeps decisions at headquarters — good for coordination, especially when subsidiaries depend on each other's inputs. Decentralization pushes decisions to lower levels/subsidiaries — beneficial in fast-changing environments, improving local responsiveness and employee morale. Structures must evolve with internal and external change.",
  "org-types":
    "Four common international structures: International Division (separates domestic from international activities); International Area (organizes operations by geographic regions — best for unique regional markets); Global Product (divides operations by product areas — overcomes coordination problems for diverse products); Global Matrix (splits the chain of command between product and area divisions — can be cumbersome with 'foggy' accountability). Work teams: self-managed teams (employees take on supervisor duties, raising productivity/quality), cross-functional teams (employees from similar levels but different departments), and global teams (top managers from HQ and subsidiaries solving company-wide problems).",
  "market-research":
    "Market research is gathering and analyzing information to help managers make good decisions — understanding customer needs and preferences and designing suitable strategies (e.g., Starbucks understanding European café culture and introducing coffee culture to tea-drinking China).",
  "market-screening":
    "Screening potential markets and sites has two goals: reduce search costs and study as many markets/sites as possible. Step 1 identifies basic appeal — firms enter international markets to increase sales/profits or to obtain resources (raw materials, labor, capital) — and assesses basic demand and resource availability. The national business environment is then assessed across cultural forces (customs, language, lifestyle, preferences), political/legal forces (regulations, bureaucracy, political stability/risk) and economic/financial forces. Logistics manages the flow of products from raw materials through manufacturing to the final customer. Online expansion considers infrastructure, content/licensing, privacy, security and intellectual property.",
  "market-potential":
    "Market potential measures the size and profitability of a market. Income elasticity measures how much demand changes as consumer income changes: an income-elastic product (elasticity > 1, e.g., jewelry, toys, luxury furniture) sees demand rise quickly with income, while an income-inelastic product (elasticity < 1, e.g., food, beverages, hygiene basics) changes little with income. When information is scarce, firms use a Market Potential Index (MPI) based on eight factors: market size, market intensity, market growth rate, market consumption capacity, commercial infrastructure, market receptivity, economic freedom and country risk. Site potential considers labor/management availability, wage rates, training needs, productivity and infrastructure. Final selection narrows to a few sites which managers visit on field trips, plus competitor analysis.",
  "research-methods":
    "Secondary market research uses pre-existing data (inside the company or from external public sources like the WTO, UN, UNCTAD, CIA World Factbook, and private industry associations or service organizations); it is cheaper and faster but can be scarce, unreliable and hard to compare across countries. Primary market research collects new original data for the current purpose: more accurate but costlier and slower. Tools include trade shows (firms exhibit products), trade missions (government-sponsored international trips), focus groups (informal interviews with 8–12 people), consumer panels (recording buying behavior/opinions), surveys (written/oral), and environmental scanning (continuous monitoring of the external environment). Challenges abroad include language, illiteracy and cultural differences, so firms often hire local agencies.",
  "entry-modes":
    "An entry mode is the institutional arrangement by which a firm gets its products, technologies, human skills or other resources into a market. The three categories are: exporting/importing and countertrade; contractual entry; and investment entry.",
  exporting:
    "Companies export to expand total sales, achieve economies of scale, diversify sales, generate more level cash flow, and gain international experience. The export strategy is a four-step model: (1) identify a potential market, (2) match needs to abilities, (3) initiate meetings (build trust), (4) commit resources (3–5 years). Direct exporting sells products directly to buyers in a target market using sales representatives (represent only their own company, don't take title) or distributors (take ownership of the merchandise in the target market). Indirect exporting sells through intermediaries who resell — agents, export management companies (EMC), export trading companies, and freight forwarders (specialists in customs clearing, tariffs, shipping and insurance).",
  countertrade:
    "Countertrade is selling goods or services that are paid for, in whole or in part, with other goods or services; developing/emerging markets use it when they lack hard currency (e.g., Pepsi in the USSR). Types: barter (the oldest form), counterpurchase (lets the country earn back some currency it paid for the original imports), offset (greater freedom in fulfilling one's end of the deal), switch trading (arranging another buyer when the trading company can't use the merchandise), and buyback (typifies long-term relationships).",
  "export-financing":
    "Export/import financing methods, ordered by risk: ADVANCE PAYMENT — the importer pays before shipment (most favorable for exporters, least for importers; used when parties are unfamiliar, the deal is small, or the buyer's credit is poor). DOCUMENTARY COLLECTION — a bank acts as intermediary without accepting financial risk, using a draft/bill of exchange (a sight draft requires payment on delivery; a time draft extends 30/60/90 days), a packing list and a bill of lading. LETTER OF CREDIT — the importer's bank pledges to pay the exporter when terms are met; the most common is an irrevocable letter of credit (changed only with both parties' approval), and a confirmed irrevocable letter of credit adds the exporter's bank's creditworthiness for a fee. OPEN ACCOUNT — the exporter ships then bills the importer (least favorable for exporters, most for importers; used between very familiar parties or subsidiaries of the same company).",
  "contractual-entry":
    "Contractual entry modes: LICENSING — a licensor grants a licensee the right to use intangible property for a limited time for royalty payments (a percentage of sales), exclusive or nonexclusive; cross-licensing is exchanging intangible property. FRANCHISING — a franchiser supplies intangible property and ongoing assistance over an extended period, where the brand/trademark is the most important item (KFC, Starbucks). MANAGEMENT CONTRACT — one company supplies another with managerial expertise for a specific period (technical or general-management knowledge). TURNKEY (Build-Operate-Transfer) PROJECT — a company designs, constructs and tests a facility for a client then transfers ownership (power plants, airports, telecom). Each spreads competency and helps nations gain infrastructure, but can create a future competitor.",
  "investment-entry":
    "Investment entry modes: WHOLLY OWNED SUBSIDIARY — a facility entirely owned and controlled by one parent (built from the ground up or by purchase); gives day-to-day control and coordination but is expensive and high risk. JOINT VENTURE — a separate company created and jointly owned by two or more independent entities for a common objective (four configurations: forward integration, backward integration, buyback, multistage); it reduces risk and aids market penetration/channel access but risks partner conflict and loss of control. STRATEGIC ALLIANCE — two or more entities cooperate without forming a separate company to achieve strategic goals (with suppliers, buyers or competitors); shares project cost and taps strengths but risks partner conflict and creating a competitor. Partner selection is crucial: a suitable partner offers something valuable, is trustworthy, and firmly commits to the agreement's goals.",
};

/* ───────────────────────────── Questions ───────────────────────────── */

const Q = (
  id: string,
  difficulty: Question["difficulty"],
  type: Question["type"],
  chapter: Chapter,
  topic: string,
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question => ({ id, difficulty, type, chapter, topic, prompt, options, correctIndex, explanation });

const questions: Question[] = [
  // ════════════════ Chapter 8 — FDI ════════════════
  Q("fdi-e1", "easy", "definition", 8, "fdi-basics",
    "Foreign Direct Investment (FDI) is best defined as:",
    ["The purchase of assets or significant ownership in a company abroad to gain management control", "A short-term loan to a foreign government", "Buying foreign stocks with no control", "Exporting goods to another country"],
    0, "FDI is buying physical assets or a significant ownership stake in a company in another country to gain a measure of management control."),
  Q("fdi-e2", "easy", "true-false", 8, "fdi-basics",
    "Portfolio investment involves obtaining a degree of management control in a company.",
    ["True", "False"], 1,
    "False. Portfolio investment does NOT involve obtaining a degree of control — that distinguishes it from FDI."),
  Q("fdi-e3", "easy", "definition", 8, "fdi-forms",
    "Buying land abroad and building new facilities from scratch is called:",
    ["Greenfield investment", "Acquisition", "Portfolio investment", "Countertrade"],
    0, "A greenfield investment is buying land in another country and building new facilities (a wholly owned subsidiary) from the ground up."),
  Q("fdi-e4", "easy", "true-false", 8, "fdi-basics",
    "In 2014, for the first time, developing nations attracted more FDI than developed nations.",
    ["True", "False"], 0,
    "True — developing nations drew about 55% of the global total in 2014, and China was the leading recipient in 2020."),
  Q("fdi-e5", "easy", "definition", 8, "balance-of-payments",
    "The national accounting system that records all receipts from and payments to foreign entities is the:",
    ["Balance of payments", "Income statement", "Gold standard", "Market potential index"],
    0, "The balance of payments records all receipts from and payments to foreign entities, via the current account and the capital account."),
  Q("fdi-m1", "medium", "multiple-choice", 8, "fdi-theories",
    "Under the Eclectic Theory, firms invest abroad when which advantages combine?",
    ["Location, ownership and internalization", "Price, place and promotion", "Land, labor and capital", "Speed, cost and quality"],
    0, "The Eclectic Theory (OLI) says firms invest when a location advantage combines with ownership and internalization advantages."),
  Q("fdi-m2", "medium", "multiple-choice", 8, "fdi-theories",
    "A firm acquires its input suppliers abroad to dominate its industry. This use of vertical integration reflects which theory of FDI?",
    ["Market power", "International product life cycle", "Market imperfections", "Balance of payments"],
    0, "The market power theory: firms invest to establish a dominant position, often via vertical integration (backward toward inputs or forward toward outputs)."),
  Q("fdi-m3", "medium", "multiple-choice", 8, "fdi-management",
    "The 'purchase-or-build' decision favors building (greenfield) when:",
    ["No suitable facilities exist or upgrading existing ones is too costly", "Ready-made staff and equipment are urgently needed", "The firm wants the fastest possible entry", "The target already has ideal facilities"],
    0, "Building is preferred when no suitable facilities exist or upgrading would be too costly — common in developing nations; acquisition gives ready facilities/staff."),
  Q("fdi-m4", "medium", "multiple-choice", 8, "fdi-management",
    "Producing each component of a product where its production cost is lowest is called:",
    ["Rationalized production", "Countertrade", "Portfolio investment", "Trade diversion"],
    0, "Rationalized production is a system in which each component is produced where its cost is lowest."),
  Q("fdi-m5", "medium", "multiple-choice", 8, "fdi-government",
    "A host country might restrict FDI by:",
    ["Imposing ownership restrictions and performance requirements", "Offering tax breaks and low-interest loans", "Building better infrastructure", "Providing investment insurance"],
    0, "Host restriction tools include ownership restrictions (e.g., in cultural or national-security industries) and performance requirements; the others are promotion tools."),
  Q("fdi-m6", "medium", "comparison", 8, "balance-of-payments",
    "Which is recorded in the CURRENT account of the balance of payments?",
    ["Exports and imports of goods and services and income", "Purchases and sales of assets", "A country's gold reserves only", "Stock prices"],
    0, "The current account records exports/imports of goods and services and income; the capital account records purchases/sales of assets."),
  Q("fdi-h1", "hard", "scenario", 8, "fdi-management",
    "Tesla builds plants abroad and its key suppliers invest nearby to stay close. This illustrates which managerial driver of FDI?",
    ["Following customers to gain/keep their business", "Rationalized production", "Trade diversion", "Revaluation"],
    0, "Firms invest abroad to follow customers when key customers invest there (e.g., Tesla's gigafactories and their suppliers); they also follow competitors ('follow the leader')."),
  Q("fdi-h2", "hard", "scenario", 8, "fdi-government",
    "A host government fears that profits earned by a foreign investor will be sent home. Its concern is mainly about:",
    ["Draining foreign-exchange reserves through profit repatriation", "Gaining new technology", "Increasing local employment", "Building national champions"],
    0, "A host-country concern is the drain on foreign-exchange reserves when profits are repatriated abroad; gaining tech and jobs are reasons FOR welcoming FDI."),
  Q("fdi-h3", "hard", "comparison", 8, "fdi-theories",
    "A limitation of the International Product Life Cycle theory is that it:",
    ["Doesn't fully explain why firms invest directly rather than license or export", "Ignores the product entirely", "Only applies to services", "Requires a currency board"],
    0, "The IPLC theory doesn't fully explain why firms choose direct investment over licensing or exporting to avoid risk."),
  Q("fdi-h4", "hard", "scenario", 8, "fdi-basics",
    "A firm buys a 3% stake in a foreign company purely for financial return, with no say in management. This is:",
    ["Portfolio investment, not FDI", "Greenfield FDI", "A merger", "Countertrade"],
    0, "Without a degree of management control it is portfolio investment, not FDI."),

  // ════════════════ Chapter 9 — Regional Integration ════════════════
  Q("ri-e1", "easy", "definition", 9, "regional-integration",
    "Regional economic integration (regionalism) is the process by which countries in a region cooperate to:",
    ["Reduce or eliminate barriers to the flow of products, people or capital", "Raise tariffs against each other", "Adopt a single global currency", "Ban all foreign investment"],
    0, "Regionalism is cooperation among countries in a geographic region to reduce/eliminate barriers to the international flow of products, people or capital."),
  Q("ri-e2", "easy", "definition", 9, "integration-levels",
    "In which level do members remove internal trade barriers but each keeps its OWN barriers against nonmembers?",
    ["Free trade area", "Customs union", "Common market", "Political union"],
    0, "A free trade area removes barriers among members while each member sets its own barriers against nonmembers."),
  Q("ri-e3", "easy", "definition", 9, "integration-levels",
    "Which level adds a COMMON trade policy against nonmembers to a free trade area?",
    ["Customs union", "Free trade area", "Political union", "Economic union"],
    0, "A customs union removes internal barriers AND sets a common trade policy against nonmembers."),
  Q("ri-e4", "easy", "true-false", 9, "trading-blocs",
    "The European Union (EU) is the most advanced example of regional integration.",
    ["True", "False"], 0, "The EU is cited as the most advanced example of regional integration."),
  Q("ri-e5", "easy", "definition", 9, "trading-blocs",
    "The GCC is a regional bloc among which nations?",
    ["Arabian Gulf nations", "Southeast Asian nations", "South American nations", "African nations"],
    0, "The Gulf Cooperation Council (GCC) is integration among Arabian Gulf nations."),
  Q("ri-m1", "medium", "multiple-choice", 9, "integration-levels",
    "A common market differs from a customs union because it also removes barriers to:",
    ["The movement of labor and capital", "Internal goods trade only", "Cultural exchange", "Tourism"],
    0, "A common market removes barriers to trade AND to the movement of labor and capital, with a common external policy."),
  Q("ri-m2", "medium", "multiple-choice", 9, "integration-levels",
    "Which level requires countries to COORDINATE their economic policies, beyond a common market?",
    ["Economic union", "Customs union", "Free trade area", "Trade diversion"],
    0, "An economic union adds coordinated economic policies on top of free movement of goods, labor and capital with a common trade policy."),
  Q("ri-m3", "medium", "multiple-choice", 9, "integration-effects",
    "An increase in trade between member nations resulting from integration is called:",
    ["Trade creation", "Trade diversion", "Arbitrage", "Countertrade"],
    0, "Trade creation is the increase in the level of trade between nations resulting from integration."),
  Q("ri-m4", "medium", "comparison", 9, "integration-effects",
    "Which is a DRAWBACK of regional integration?",
    ["Loss of national sovereignty", "Greater consensus", "Political cooperation", "Corporate savings"],
    0, "Loss of national sovereignty is a drawback; greater consensus, cooperation and corporate savings are benefits."),
  Q("ri-m5", "medium", "multiple-choice", 9, "trading-blocs",
    "NAFTA/USMCA is integration among which countries?",
    ["USA, Canada and Mexico", "Brazil, Argentina and Uruguay", "Germany, France and Italy", "China, Japan and Korea"],
    0, "NAFTA (now USMCA) integrates the USA, Canada and Mexico."),
  Q("ri-h1", "hard", "scenario", 9, "integration-effects",
    "After joining a bloc, a country starts importing from a less-efficient member instead of a cheaper nonmember. This is:",
    ["Trade diversion", "Trade creation", "Greater consensus", "An economies-of-scale gain"],
    0, "Trade diversion is the diversion of trade away from more efficient nonmembers toward less efficient member nations."),
  Q("ri-h2", "hard", "scenario", 9, "integration-levels",
    "A group of countries shares free movement of goods, labor and capital, a common external tariff, coordinated economic policies, AND coordinated political systems. This is a:",
    ["Political union", "Economic union", "Common market", "Customs union"],
    0, "Political union is the deepest level — economic and political integration with coordinated economic and political systems."),
  Q("ri-h3", "hard", "comparison", 9, "integration-effects",
    "Critics of NAFTA argued some US jobs moved to Mexico. This concern reflects which drawback?",
    ["Shifts in employment", "Trade creation", "Greater consensus", "Corporate savings"],
    0, "Shifts in employment: jobs may move to nations with lower wages or higher efficiency."),

  // ════════════════ Chapter 11 — Monetary System ════════════════
  Q("ms-e1", "easy", "definition", 11, "currency-values",
    "Intentionally lowering a currency's value to boost exports is called:",
    ["Devaluation", "Revaluation", "Arbitrage", "Revaluation tax"],
    0, "Devaluation is intentionally lowering a currency's value (which boosts exports); revaluation raises it."),
  Q("ms-e2", "easy", "true-false", 11, "currency-values",
    "A weak (depreciating) currency lowers a country's export prices and raises its import prices.",
    ["True", "False"], 0,
    "True — a weak currency makes exports cheaper abroad and imports more expensive, helping firms gain market share."),
  Q("ms-e3", "easy", "definition", 11, "exchange-determinants",
    "The idea that an identical product should cost the same in all countries (in a common currency) is the:",
    ["Law of one price", "Big Mac Index", "Gold standard", "Currency board"],
    0, "The law of one price says an identical product must have an identical price in all countries when expressed in a common currency."),
  Q("ms-e4", "easy", "definition", 11, "ppp",
    "The Economist's simplified, real-world measure of purchasing power parity is the:",
    ["Big Mac Index", "Par value", "SDR", "Bill of lading"],
    0, "The Big Mac Index is used by The Economist as a simplified PPP measure."),
  Q("ms-e5", "easy", "definition", 11, "fixed-rates",
    "Under the gold standard, the value at which a currency was linked to gold was called the:",
    ["Par value", "Spot rate", "Arbitrage rate", "Float"],
    0, "The gold standard linked paper currency to specific values of gold — the par value."),
  Q("ms-e6", "easy", "definition", 11, "fixed-rates",
    "The 1944 agreement that based the system on the US dollar fixed at $35/oz of gold was:",
    ["Bretton Woods", "The Jamaica Agreement", "The Smithsonian Agreement", "Maastricht"],
    0, "The Bretton Woods Agreement (1944) fixed the dollar at $35/oz of gold and created the World Bank and IMF."),
  Q("ms-m1", "medium", "comparison", 11, "currency-values",
    "In the EFFICIENT market view of exchange rates:",
    ["Prices reflect all publicly available information, and forward rates are accurate forecasts", "Prices ignore public information", "Private information always beats the market", "Forecasting is impossible"],
    0, "The efficient market view holds that prices reflect all public information and forward rates are accurate forecasts."),
  Q("ms-m2", "medium", "comparison", 11, "currency-values",
    "Which forecasting technique uses charts of past currency price trends?",
    ["Technical analysis", "Fundamental analysis", "Par value analysis", "PESTLE analysis"],
    0, "Technical analysis uses charts of past trends; fundamental analysis uses economic indicators (inflation, interest rates, etc.)."),
  Q("ms-m3", "medium", "multiple-choice", 11, "ppp",
    "According to PPP, a country with high inflation will tend to see its currency:",
    ["Depreciate", "Appreciate", "Stay perfectly fixed", "Become a reserve currency"],
    0, "High inflation erodes purchasing power, so the currency depreciates; exchange rates adjust to inflation differences."),
  Q("ms-m4", "medium", "multiple-choice", 11, "exchange-determinants",
    "A government buying and selling government securities to affect interest rates/money supply is using:",
    ["Monetary policy", "Fiscal policy", "Trade policy", "A currency board"],
    0, "Monetary policy directly affects interest rates or the money supply (e.g., buying/selling government securities); fiscal policy works via taxes and spending."),
  Q("ms-m5", "medium", "multiple-choice", 11, "floating-rates",
    "A 'managed float' means currencies:",
    ["Float, but governments intervene to stabilize them at target rates", "Are fixed to gold permanently", "Never change value", "Are banned from trading"],
    0, "A managed float lets currencies float with government intervention to stabilize at target rates; a free float has none."),
  Q("ms-m6", "medium", "definition", 11, "floating-rates",
    "A commitment to exchange domestic currency for a specific foreign currency at a fixed rate is a:",
    ["Currency board", "Pegged guess", "Free float", "Par value"],
    0, "A currency board is a commitment to exchange domestic currency for a specific foreign currency at a fixed rate."),
  Q("ms-h1", "hard", "scenario", 11, "exchange-determinants",
    "A product is much cheaper in Country A than Country B (same common currency). A trader buys low and resells high. This opportunity is called:",
    ["Arbitrage", "Devaluation", "A managed float", "Counterpurchase"],
    0, "A failure of the law of one price creates an arbitrage opportunity — quick purchase and resale for profit."),
  Q("ms-h2", "hard", "scenario", 11, "ppp",
    "Why does PPP predict LONG-term exchange rates better than short-term?",
    ["Short-term rates are distorted by transport costs, trade barriers and business psychology", "Long-term data does not exist", "Inflation never matters", "Governments forbid short-term trading"],
    0, "PPP is better long-term (10+ years); short-term it is poor due to transportation costs, trade barriers and business confidence/psychology."),
  Q("ms-h3", "hard", "scenario", 11, "fixed-rates",
    "The gold standard ultimately collapsed (by 1939) largely because countries:",
    ["Printed money aggressively and engaged in competitive devaluations", "Refused to ever devalue", "Adopted the euro", "Created the IMF too early"],
    0, "It collapsed due to aggressive printing of paper money (inflation) and retaliatory competitive devaluations."),
  Q("ms-h4", "hard", "definition", 11, "floating-rates",
    "'Moral hazard' in the international monetary system refers to the risk that:",
    ["IMF bailouts reduce caution in private lending", "Currencies float without limit", "Inflation is always zero", "Gold reserves are unlimited"],
    0, "Moral hazard is the concern that IMF bailouts might reduce caution in private lending."),

  // ════════════════ Chapter 12 — Strategy & Organization ════════════════
  Q("so-e1", "easy", "definition", 12, "company-analysis",
    "A 'core competency' is best described as:",
    ["A special ability difficult for competitors to equal", "The company's cheapest product", "A government regulation", "A type of tax"],
    0, "A core competency is a special ability difficult for competitors to equal, combining multiple coordinated skills."),
  Q("so-e2", "easy", "definition", 12, "company-analysis",
    "Dividing a firm's activities into primary and support activities to find value creation is called:",
    ["Value chain analysis", "PESTLE analysis", "Countertrade", "Arbitrage"],
    0, "Value chain analysis divides activities into primary (logistics, production, marketing, sales, service) and support (infrastructure, HR, technology, procurement)."),
  Q("so-e3", "easy", "definition", 12, "business-strategies",
    "Designing unique products to enjoy higher prices and customer loyalty is which business-level strategy?",
    ["Differentiation", "Low-cost leadership", "Focus", "Retrenchment"],
    0, "Differentiation designs unique products to command higher prices and build loyalty."),
  Q("so-e4", "easy", "true-false", 12, "intl-strategies",
    "A global strategy offers the same products and marketing in all markets.",
    ["True", "False"], 0,
    "True — a global strategy standardizes products and marketing across markets to capture scale and location economies."),
  Q("so-e5", "easy", "definition", 12, "org-types",
    "A team of employees from similar levels but different departments (e.g., purchasing and marketing) is a:",
    ["Cross-functional team", "Self-managed team", "Global team", "Board of directors"],
    0, "A cross-functional team draws employees from similar levels but different departments."),
  Q("so-m1", "medium", "comparison", 12, "intl-strategies",
    "A key DRAWBACK of a multinational (multidomestic) strategy is that it:",
    ["Cannot exploit scale economies and has a higher cost structure", "Ignores local preferences", "Standardizes everything", "Is always the cheapest option"],
    0, "Multidomestic strategy adapts to local preferences (high value) but cannot exploit scale economies, raising the cost structure."),
  Q("so-m2", "medium", "comparison", 12, "intl-strategies",
    "A risk of a GLOBAL strategy is that it may:",
    ["Overlook important local differences in preferences", "Cost too much due to customization", "Prevent any knowledge sharing", "Eliminate economies of scale"],
    0, "A global strategy's standardization can overlook important local differences in preferences."),
  Q("so-m3", "medium", "multiple-choice", 12, "corporate-strategies",
    "Closing factories and laying off staff due to poor conditions is which corporate-level strategy?",
    ["Retrenchment", "Growth", "Stability", "Combination"],
    0, "Retrenchment reduces scale/scope (closing factories, layoffs) in response to poor conditions."),
  Q("so-m4", "medium", "multiple-choice", 12, "company-analysis",
    "PESTLE analysis examines which set of factors?",
    ["Political, Economic, Social, Technological, Legal, Environmental", "Price, Earnings, Sales, Tax, Labor, Equity", "People, Energy, Systems, Trade, Land, Exports", "Product, Promotion, Place, Price, Logistics, Ethics"],
    0, "PESTLE = Political, Economic, Social, Technological, Legal and Environmental factors."),
  Q("so-m5", "medium", "comparison", 12, "org-structure",
    "Decentralization (pushing decisions to subsidiaries) is especially beneficial when:",
    ["The environment changes fast and local responsiveness matters", "Subsidiaries depend heavily on each other's inputs", "Headquarters must control everything", "There are no local managers"],
    0, "Decentralization helps in fast-changing environments, improving local responsiveness and morale; centralization suits interdependent subsidiaries."),
  Q("so-m6", "medium", "multiple-choice", 12, "org-types",
    "Which structure organizes global operations by geographic regions and suits unique regional markets?",
    ["International area structure", "Global product structure", "International division structure", "Global matrix structure"],
    0, "The international area structure organizes operations by geographic regions — best for unique regional markets."),
  Q("so-h1", "hard", "scenario", 12, "business-strategies",
    "Ryanair offers 'no-frills' flights ~50% cheaper than national carriers using secondary airports. This is which business-level strategy?",
    ["Low-cost leadership", "Differentiation", "Focus differentiation", "Retrenchment"],
    0, "Ryanair exploits economies of scale and cost savings for the lowest cost structure — low-cost leadership."),
  Q("so-h2", "hard", "scenario", 12, "org-types",
    "A firm splits its chain of command between product and area divisions, but accountability becomes 'foggy'. This describes the:",
    ["Global matrix structure", "International division structure", "Global product structure", "International area structure"],
    0, "The global matrix splits command between product and area divisions and can be cumbersome with foggy accountability."),
  Q("so-h3", "hard", "comparison", 12, "intl-strategies",
    "A company selling identical smartphones worldwide to cut costs, but losing share where tastes differ, shows the core trade-off between:",
    ["Global (standardization) vs. multidomestic (local adaptation) strategy", "Growth vs. retrenchment", "Centralization vs. a currency board", "Barter vs. offset"],
    0, "It's the classic global vs. multidomestic trade-off: scale-economy savings vs. responsiveness to local preferences."),
  Q("so-h4", "hard", "multiple-choice", 12, "company-analysis",
    "At which level are objectives typically the most precise and numerical?",
    ["Department level", "Highest (corporate) level", "Mission statement", "Stakeholder level"],
    0, "Objectives become more concrete down the hierarchy: highest level is general, business-unit specific, and department level precise/numerical."),

  // ════════════════ Chapter 13 — Analyzing Opportunities ════════════════
  Q("ao-e1", "easy", "definition", 13, "market-research",
    "Market research is the process of:",
    ["Gathering and analyzing information to help managers make good decisions", "Selling products directly to consumers", "Setting exchange rates", "Building factories abroad"],
    0, "Market research gathers and analyzes information to help managers make good decisions."),
  Q("ao-e2", "easy", "true-false", 13, "market-screening",
    "Two goals of screening markets and sites are to reduce search costs and study as many markets as possible.",
    ["True", "False"], 0, "Correct — the two screening goals are reducing search costs and examining as many markets/sites as possible."),
  Q("ao-e3", "easy", "definition", 13, "research-methods",
    "Research that uses pre-existing data from inside the firm or external sources is:",
    ["Secondary market research", "Primary market research", "A focus group", "A trade mission"],
    0, "Secondary research uses already-existing data; it is cheaper and faster but can be scarce or unreliable."),
  Q("ao-e4", "easy", "definition", 13, "research-methods",
    "An informal interview with a small group of 8–12 people to learn opinions and attitudes is a:",
    ["Focus group", "Survey", "Consumer panel", "Trade show"],
    0, "A focus group is an informal interview with 8–12 people to surface opinions, impressions and consumer attitudes."),
  Q("ao-e5", "easy", "definition", 13, "market-potential",
    "Income elasticity measures how much demand changes when:",
    ["Consumer income changes", "Exchange rates change", "Tariffs change", "The weather changes"],
    0, "Income elasticity measures how strongly demand responds to a change in consumer income."),
  Q("ao-m1", "medium", "multiple-choice", 13, "market-screening",
    "Two basic reasons firms enter international markets are to increase sales/profits and to:",
    ["Obtain resources such as raw materials, labor and capital", "Avoid all market research", "Eliminate competitors instantly", "Fix their currency"],
    0, "Firms enter to increase sales/profits OR to obtain resources (raw materials, labor, capital)."),
  Q("ao-m2", "medium", "comparison", 13, "market-potential",
    "Jewelry and luxury furniture, whose demand rises quickly as income grows, are:",
    ["Income-elastic products (elasticity > 1)", "Income-inelastic products (elasticity < 1)", "Inferior goods", "Free goods"],
    0, "Income-elastic products (elasticity > 1, e.g., jewelry, toys, luxury furniture) see demand rise quickly with income."),
  Q("ao-m3", "medium", "comparison", 13, "market-potential",
    "Food and basic hygiene products, whose demand barely changes with income, are:",
    ["Income-inelastic (elasticity < 1)", "Income-elastic (elasticity > 1)", "Luxury goods", "Capital goods"],
    0, "Income-inelastic products (elasticity < 1, e.g., food, beverages, hygiene basics) change little with income."),
  Q("ao-m4", "medium", "multiple-choice", 13, "market-potential",
    "When information is scarce, firms rank country attractiveness using the:",
    ["Market Potential Index (MPI)", "Big Mac Index", "Balance of payments", "Bill of lading"],
    0, "The Market Potential Index (MPI) ranks markets using eight factors (size, intensity, growth, consumption, infrastructure, receptivity, economic freedom, country risk)."),
  Q("ao-m5", "medium", "multiple-choice", 13, "research-methods",
    "Which is an advantage of PRIMARY market research over secondary?",
    ["It is more accurate and fills gaps in existing data", "It is always cheaper", "It is always faster", "It needs no data collection"],
    0, "Primary research collects new original data — more accurate and addresses gaps — but it is costlier and slower."),
  Q("ao-m6", "medium", "multiple-choice", 13, "market-screening",
    "Managing the flow of products from raw materials through manufacturing to the final customer is:",
    ["Logistics", "Countertrade", "Arbitrage", "Franchising"],
    0, "Logistics manages the flow of products from raw materials to manufacturing to the final customer."),
  Q("ao-h1", "hard", "scenario", 13, "market-potential",
    "A firm finds a country has high market size and growth but very high country risk and weak economic freedom. These four items are part of the:",
    ["Market Potential Index factors", "Value chain", "Balance of payments", "Four-step export model"],
    0, "Market size, growth, country risk and economic freedom are among the eight MPI factors."),
  Q("ao-h2", "hard", "scenario", 13, "research-methods",
    "A company conducting surveys abroad faces high illiteracy and language differences, so it:",
    ["Often hires a local research agency to run the study", "Cancels all research", "Uses only its home-country data", "Relies solely on exchange rates"],
    0, "Because of language, illiteracy and cultural differences, firms often hire local research agencies."),
  Q("ao-h3", "hard", "comparison", 13, "research-methods",
    "Continuous monitoring of the external environment to spot opportunities and threats is called:",
    ["Environmental scanning", "A consumer panel", "A trade mission", "A turnkey project"],
    0, "Environmental scanning is the continuous monitoring of the external environment for opportunities, threats and market changes."),

  // ════════════════ Chapter 14 — Entry Modes ════════════════
  Q("em-e1", "easy", "definition", 14, "entry-modes",
    "An 'entry mode' is:",
    ["The institutional arrangement by which a firm gets its resources into a market", "A type of exchange rate", "A tax on imports", "A market research tool"],
    0, "An entry mode is the institutional arrangement by which a firm gets its products, technologies, skills or resources into a market."),
  Q("em-e2", "easy", "definition", 14, "countertrade",
    "Paying for goods or services, wholly or partly, with other goods or services is:",
    ["Countertrade", "A letter of credit", "Open account", "Arbitrage"],
    0, "Countertrade is selling goods/services paid for, in whole or part, with other goods/services — used when hard currency is scarce."),
  Q("em-e3", "easy", "definition", 14, "countertrade",
    "The oldest known form of countertrade is:",
    ["Barter", "Offset", "Switch trading", "Buyback"],
    0, "Barter is the oldest known form of countertrade."),
  Q("em-e4", "easy", "definition", 14, "contractual-entry",
    "When a franchiser supplies a franchisee with intangible property and ongoing assistance, the MOST important item to the franchisee is the:",
    ["Brand name or trademark", "Factory building", "Currency board", "Bill of lading"],
    0, "In franchising the brand name/trademark is the most important item for the franchisee (e.g., KFC, Starbucks)."),
  Q("em-e5", "easy", "definition", 14, "investment-entry",
    "A facility entirely owned and controlled by a single parent company is a:",
    ["Wholly owned subsidiary", "Joint venture", "Strategic alliance", "Franchise"],
    0, "A wholly owned subsidiary is entirely owned and controlled by one parent (built or purchased)."),
  Q("em-e6", "easy", "true-false", 14, "export-financing",
    "Under 'advance payment', the importer pays the exporter before the merchandise is shipped.",
    ["True", "False"], 0,
    "True — advance payment means the importer pays before shipment (most favorable for exporters)."),
  Q("em-m1", "medium", "multiple-choice", 14, "exporting",
    "Which is the correct order of the four-step export strategy model?",
    ["Identify market → match needs to abilities → initiate meetings → commit resources", "Commit resources → identify market → initiate meetings → match needs", "Initiate meetings → commit resources → identify market → match needs", "Match needs → commit resources → identify market → initiate meetings"],
    0, "The four steps are: identify a potential market, match needs to abilities, initiate meetings (build trust), commit resources (3–5 years)."),
  Q("em-m2", "medium", "comparison", 14, "exporting",
    "The main difference between direct and indirect exporting is that indirect exporting:",
    ["Sells through intermediaries who resell to buyers", "Sells directly to buyers in the target market", "Never uses agents", "Requires building a factory abroad"],
    0, "Direct exporting sells directly to buyers; indirect exporting sells through intermediaries (agents, EMCs, trading companies) who resell."),
  Q("em-m3", "medium", "multiple-choice", 14, "exporting",
    "A specialist in customs clearing, tariff schedules, shipping and insurance fees is a:",
    ["Freight forwarder", "Sales representative", "Licensor", "Franchisee"],
    0, "A freight forwarder specializes in export-related activities such as customs clearing, tariffs, shipping and insurance."),
  Q("em-m4", "medium", "multiple-choice", 14, "export-financing",
    "In which method does a bank act as an intermediary WITHOUT accepting financial risk?",
    ["Documentary collection", "Advance payment", "Open account", "Letter of credit"],
    0, "Documentary collection uses a bank as an intermediary without accepting financial risk (via draft, packing list, bill of lading)."),
  Q("em-m5", "medium", "multiple-choice", 14, "export-financing",
    "When the importer's bank issues a letter pledging to pay the exporter once terms are met, this is a:",
    ["Letter of credit", "Open account", "Advance payment", "Counterpurchase"],
    0, "A letter of credit is the importer's bank's pledge to pay the exporter when the exporter fulfills the terms."),
  Q("em-m6", "medium", "multiple-choice", 14, "contractual-entry",
    "A company designs, constructs and tests a power plant for a client, then transfers ownership. This is a:",
    ["Turnkey (Build-Operate-Transfer) project", "Joint venture", "Licensing deal", "Wholly owned subsidiary"],
    0, "A turnkey/BOT project: the firm designs, builds and tests a facility (e.g., power plant, airport) then transfers ownership."),
  Q("em-m7", "medium", "multiple-choice", 14, "contractual-entry",
    "Licensing typically compensates the licensor through:",
    ["Royalty payments based on a percentage of the licensee's sales", "A one-time gift", "Equity in the licensee only", "Customs duties"],
    0, "Licensing grants use of intangible property for royalty payments based on a percentage of the licensee's sales revenue."),
  Q("em-m8", "medium", "comparison", 14, "investment-entry",
    "A strategic alliance differs from a joint venture mainly because the alliance:",
    ["Does NOT form a separate company", "Always forms a separate company", "Cannot involve competitors", "Requires full ownership"],
    0, "A strategic alliance is cooperation to achieve strategic goals WITHOUT forming a separate company; a joint venture creates a separate jointly owned company."),
  Q("em-h1", "hard", "scenario", 14, "export-financing",
    "Two firms have never dealt before, the order is small, and the buyer's credit is poor. Which financing best protects the exporter?",
    ["Advance payment", "Open account", "Documentary collection", "Time draft"],
    0, "Advance payment is most favorable for exporters and is used exactly when parties are unfamiliar, the deal is small, or the buyer's credit is poor."),
  Q("em-h2", "hard", "scenario", 14, "export-financing",
    "Which method carries the GREATEST risk for the exporter (most favorable to the importer)?",
    ["Open account", "Advance payment", "Letter of credit", "Confirmed irrevocable letter of credit"],
    0, "Open account (ship now, bill later) is least favorable for exporters and most favorable for importers."),
  Q("em-h3", "hard", "scenario", 14, "contractual-entry",
    "A government hires a firm to run its electricity grid for a set period, supplying managerial expertise. This is a:",
    ["Management contract", "Turnkey project", "Franchise", "Joint venture"],
    0, "A management contract supplies another organization with managerial expertise for a specific period (e.g., running a power grid)."),
  Q("em-h4", "hard", "comparison", 14, "investment-entry",
    "A key DISADVANTAGE shared by joint ventures and strategic alliances is:",
    ["Partner conflict and possible loss of control / creating a competitor", "They require no partner at all", "They guarantee total control", "They have zero cost"],
    0, "Both risk partner conflict and loss of control, and alliances/JVs can create a future competitor."),
  Q("em-h5", "hard", "scenario", 14, "countertrade",
    "A trading company receives goods it cannot use, so it arranges another buyer who needs them. This is:",
    ["Switch trading", "Barter", "Offset", "Buyback"],
    0, "Switch trading: when the trading company has no use for the merchandise, it arranges another buyer to make the purchase."),
  Q("em-h6", "hard", "comparison", 14, "investment-entry",
    "A wholly owned subsidiary's main trade-off versus a joint venture is:",
    ["Full day-to-day control, but expensive and high risk", "Low cost, but no control", "Shared risk, but foggy accountability", "No assets risked, but creates a competitor"],
    0, "A wholly owned subsidiary gives full control and coordination but is expensive and high risk; JVs reduce risk but cost control."),

  // ── Additional hard items to deepen the hard pool ──
  Q("fdi-h5", "hard", "comparison", 8, "fdi-theories",
    "Under the market imperfections (internalization) theory, a firm invests directly in order to:",
    ["Internalize a transaction and remove an imperfection that makes markets inefficient", "Follow the international product life cycle exactly", "Establish a currency board", "Diversify its bond portfolio"],
    0, "Market imperfections theory: when imperfections (trade barriers, specialized knowledge) make transactions inefficient, the firm internalizes the transaction to remove the imperfection."),
  Q("fdi-h6", "hard", "scenario", 8, "fdi-government",
    "A home government offers exporters insurance, loans and tax breaks and pressures other states to open up. These are home-country tools of:",
    ["Promotion of outward FDI", "Restriction of FDI", "Trade diversion", "Countertrade"],
    0, "Home-country promotion tools include insurance, loans, tax breaks and political pressure; restriction would be differential taxes or sanctions."),
  Q("ri-h4", "hard", "scenario", 9, "trading-blocs",
    "MERCOSUR and the Andean Community (CAN) are examples of regional integration in:",
    ["South America", "Southeast Asia", "Western Europe", "North Africa"],
    0, "MERCOSUR (Southern Common Market) and the Andean Community (CAN) are South American integration efforts."),
  Q("ms-h5", "hard", "scenario", 11, "fixed-rates",
    "Which institution, created at Bretton Woods, financed post-WWII reconstruction and developing countries?",
    ["The World Bank", "The IMF", "The WTO", "The Federal Reserve"],
    0, "The World Bank financed post-WWII reconstruction and developing countries; the IMF regulated the system and created SDRs."),
  Q("so-h5", "hard", "scenario", 12, "corporate-strategies",
    "A conglomerate grows one unit, holds another steady, and shrinks a third at the same time. This overall approach is a:",
    ["Combination strategy", "Pure growth strategy", "Pure retrenchment strategy", "Pure stability strategy"],
    0, "A combination strategy mixes growth, stability and retrenchment across different business units."),
  Q("so-h6", "hard", "comparison", 12, "org-structure",
    "Centralized decision-making is MOST appropriate when:",
    ["Subsidiaries depend heavily on one another's inputs and need tight coordination", "Markets change very fast locally", "Local responsiveness is the top priority", "Employee morale requires local autonomy"],
    0, "Centralization aids coordination, especially when subsidiaries depend on each other's inputs; fast-changing local needs favor decentralization."),
  Q("ao-h4", "hard", "comparison", 13, "research-methods",
    "A drawback of secondary data in international research is that it:",
    ["May be scarce, unreliable, and hard to compare across countries", "Is always more expensive than primary data", "Requires running new field studies", "Cannot give a general view of a market"],
    0, "Secondary data is cheaper/faster but can be scarce, of low reliability, and difficult to compare across countries."),
  Q("em-h7", "hard", "scenario", 14, "export-financing",
    "An exporter draws a draft requiring payment 60 days after delivery. This instrument is a:",
    ["Time draft", "Sight draft", "Letter of credit", "Bill of lading"],
    0, "A time draft extends the payment period (30/60/90 days); a sight draft requires payment when goods are delivered."),

  // ── Further hard items to ensure a full 30-question hard exam ──
  Q("fdi-h7", "hard", "comparison", 8, "fdi-forms",
    "Compared with a greenfield investment, a cross-border acquisition's main advantage is that it:",
    ["Provides ready facilities, equipment and staff and a fast foothold", "Always costs less in the long run", "Avoids any integration challenges", "Guarantees full government approval"],
    0, "An acquisition gives a quick foothold with ready facilities/equipment/staff; greenfield builds from scratch when no suitable facilities exist."),
  Q("ri-h5", "hard", "comparison", 9, "integration-levels",
    "The key step that turns a free trade area into a customs union is:",
    ["Adopting a common external trade policy against nonmembers", "Allowing free movement of labor", "Coordinating fiscal policy", "Creating a single currency"],
    0, "A customs union adds a common external trade policy to the removal of internal barriers; free labor movement comes only at the common-market stage."),
  Q("ms-h6", "hard", "scenario", 11, "currency-values",
    "A firm sources components from a weak-currency country and sells in a strong-currency market. The currency effect on its profits is generally:",
    ["Favorable — lower input costs and higher-value revenue", "Unfavorable — higher costs and lower revenue", "Neutral in all cases", "Impossible to determine"],
    0, "Selling in strong-currency markets while sourcing from weak-currency countries improves profits."),
  Q("ms-h7", "hard", "comparison", 11, "floating-rates",
    "A pegged exchange rate differs from a currency board mainly because a currency board:",
    ["Is a firm commitment to exchange at a fixed rate for a specific currency", "Lets the currency float freely", "Requires no foreign reserves", "Bans all foreign exchange"],
    0, "A currency board is a strict commitment to exchange domestic currency for a specific foreign currency at a fixed rate; a peg merely ties to a more stable currency."),
  Q("so-h7", "hard", "scenario", 12, "org-types",
    "A firm with very diverse product lines suffering coordination problems across them would benefit most from a:",
    ["Global product structure", "International area structure", "International division structure", "Self-managed team"],
    0, "The global product structure divides operations by product areas and overcomes coordination problems for diverse products."),
  Q("ao-h5", "hard", "comparison", 13, "market-potential",
    "Two countries have equal market size, but one scores far lower on country risk and economic freedom. An MPI ranking would:",
    ["Rate the lower-risk, freer market as more attractive", "Rank them identically", "Ignore risk entirely", "Use only population"],
    0, "MPI weighs eight factors including country risk and economic freedom, so the lower-risk, freer market ranks higher despite equal size."),
  Q("em-h8", "hard", "comparison", 14, "contractual-entry",
    "A shared disadvantage of licensing, franchising and turnkey projects is that they can:",
    ["Create a future competitor", "Require full equity ownership", "Eliminate all royalty income", "Prevent any market entry"],
    0, "Each contractual mode can create a future competitor (and licensing/franchising can reduce control/consistency)."),
  Q("em-h9", "hard", "scenario", 14, "investment-entry",
    "Caterpillar and Mitsubishi form a separate, jointly owned company to enter a market and share channels. This is a:",
    ["Joint venture", "Wholly owned subsidiary", "Management contract", "Franchise"],
    0, "A joint venture is a separate company jointly owned by independent entities for a common objective, aiding market penetration and channel access."),
];

/* ───────────────────────────── Subject ───────────────────────────── */

export const internationalBusiness: Subject = {
  id: "international-business",
  name: { en: "International Business", ar: "الأعمال الدولية" },
  tagline: {
    en: "FDI, Trade Blocs, Currencies, Strategy & Entry Modes · Ch 8, 9, 11, 12, 13, 14",
    ar: "الاستثمار، التكتلات، العملات، الاستراتيجية وأنماط الدخول · الفصول ٨ و٩ و١١ و١٢ و١٣ و١٤",
  },
  icon: "Globe2",
  accent: "#22d3ee",
  glow: "rgba(6, 182, 212, 0.45)",
  chapters: [8, 9, 11, 12, 13, 14],
  chapterTitles: {
    8: { en: "Foreign Direct Investment", ar: "الاستثمار الأجنبي المباشر" },
    9: { en: "Regional Economic Integration", ar: "التكامل الاقتصادي الإقليمي" },
    11: { en: "The International Monetary System", ar: "النظام النقدي الدولي" },
    12: { en: "International Strategy & Organization", ar: "الاستراتيجية والتنظيم الدولي" },
    13: { en: "Analyzing International Opportunities", ar: "تحليل الفرص الدولية" },
    14: { en: "Selecting & Managing Entry Modes", ar: "اختيار وإدارة أنماط الدخول" },
  },
  topics,
  questions,
  knowledge,
  available: true,
};
